# Notebook 01 — Structure du catalogue Steam

## Objectif du notebook

Ce notebook constitue la première étape du projet.  
Son objectif est de **comprendre la structure du dataset Steam et de préparer les données pour les analyses exploratoires**.

Le dataset utilisé est un **fichier JSON semi-structuré**, ce qui signifie que certaines informations sont stockées dans des structures imbriquées ou sous forme de listes. Avant de réaliser des analyses de marché, il est donc nécessaire d’examiner et de transformer ces données.

## Dataset utilisé

Le dataset est disponible dans un bucket S3 :

s3://full-stack-bigdata-datasets/Big_Data/Project_Steam/steam_game_output.json

## Enjeux techniques

Le dataset étant **semi-structuré**, plusieurs opérations sont nécessaires pour l’exploiter correctement :

- inspection du **schéma Spark**
- exploration des **structures imbriquées**
- manipulation des **tableaux et objets JSON**
- transformation de certaines colonnes

## Étapes du notebook

Les principales étapes de ce notebook sont les suivantes :

1. **Préparation des données**  
   Chargement du dataset JSON dans PySpark, exploration du schéma Spark et transformation des structures imbriquées afin de construire une table exploitable pour l’analyse.

2. **Création de dataframes auxiliaires**  
   Construction de tables spécifiques permettant d’analyser certaines dimensions du catalogue, notamment les **tags, les plateformes, les catégories et les éditeurs**.

3. **Analyse de la croissance du catalogue Steam**  
   Étude de l’évolution du nombre de jeux publiés et du nombre d’éditeurs actifs au fil du temps.

4. **Analyse des principales caractéristiques du catalogue**  
   Exploration de plusieurs dimensions structurantes du catalogue Steam :
   - structure des éditeurs
   - plateformes supportées
   - langues disponibles

5. **Analyse des types de jeux présents sur la plateforme**  
   Étude des **catégories de gameplay** et de la **distribution des genres**, afin de mieux comprendre la composition du catalogue et le poids des productions indépendantes.

Les observations issues de cette analyse descriptive serviront de base aux analyses plus approfondies réalisées dans le **Notebook 02**.

# 1. Préparation des données

### 1.1 Chargement des données

In [0]:
import pandas as pd
from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.utils import IllegalArgumentException
from pyspark.sql.functions import col, map_from_arrays, array, lit, explode
from pyspark.sql.functions import count
from pyspark.sql.window import Window
import math
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [0]:
spark

In [0]:
df = spark.read.json(
"s3://full-stack-bigdata-datasets/Big_Data/Project_Steam/steam_game_output.json"
)

display(df)

data,id
"List(10, List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP), 13990, Valve, 0, Action, https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513, 999, English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean, Counter-Strike, 5199, 10,000,000 .. 20,000,000, List(true, true, true), 201215, 999, Valve, 2000/11/1, 0, Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role., List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192), game, )",10
"List(1000000, List(Single-player, Partial Controller Support, Steam Achievements, Steam Cloud), 0, IndigoBlue Game Studio, 0, Action, Adventure, Indie, https://cdn.akamai.steamstatic.com/steam/apps/1000000/header.jpg?t=1655723048, 999, English, Korean, Simplified Chinese, ASCENXION, 5, 0 .. 20,000, List(false, false, true), 27, 999, PsychoFlux Entertainment, 2021/05/14, 0, ASCENXION is a 2D shoot 'em up game where you explore the field to progress. Players must overcome puzzles, traps, elite units, boss fights, and other various obstacles while navigating the field. Grow stronger through rewards earned, to uncover the truth of this world., List(null, null, null, 159, null, null, null, null, null, null, null, null, null, null, null, null, 111, 138, null, null, null, null, null, 73, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 88, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 179, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 124, null, null, null, null, null, null, 148, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 161, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 51, null, null, null, null, null, null, null, 38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 69, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 181, null, null, null, 136, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 100, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 186, 159, null, null, 175, null, null, 71, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 170, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000000
"List(1000010, List(Single-player, Partial Controller Support, Steam Achievements, Steam Cloud, Steam Trading Cards), 99, NEXT Studios, 70, Adventure, Indie, RPG, Strategy, https://cdn.akamai.steamstatic.com/steam/apps/1000010/header.jpg?t=1655724189, 1999, Simplified Chinese, English, Japanese, Traditional Chinese, French, German, Spanish - Spain, Russian, Portuguese - Brazil, Crown Trick, 646, 200,000 .. 500,000, List(false, false, true), 4032, 599, Team17, NEXT Studios, 2020/10/16, 0, Enter a labyrinth that moves as you move, where mastering the elements is key to defeating enemies and uncovering the mysteries of this underground world. With a new experience awaiting every time you enter the dungeon, let the power bestowed by the crown guide you in this challenging adventure!, List(null, null, null, 205, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 179, null, 225, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 189, null, null, null, null, null, null, null, 225, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 179, null, null, null, null, 217, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 171, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 231, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 237, null, null, null, null, null, null, null, null, null, null, 192, null, null, null, null, null, 268, 226, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 211, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 225, null, null, null, null, null, null, null, null, null, null, 184, null, null, null, null, null, null, null, null, null, null, null, null, null, 178, null, null, null, null, null, null, null, null, null, null, null, 222, 254, 216, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000010
"List(1000030, List(Multi-player, Single-player, Co-op, Steam Achievements, Steam Cloud, Shared/Split Screen, Full controller support, Steam Trading Cards, Shared/Split Screen Co-op, Remote Play on Phone, Remote Play on Tablet, Remote Play on TV, Remote Play Together), 76, Vertigo Gaming Inc., 0, Action, Indie, Simulation, Strategy, https://cdn.akamai.steamstatic.com/steam/apps/1000030/header.jpg?t=1660866300, 1999, English, Cook, Serve, Delicious! 3?!, 115, 100,000 .. 200,000, List(false, true, true), 1575, 1999, Vertigo Gaming Inc., 2020/10/14, 0, Cook, serve and manage your food truck as you dish out hundreds of different foods across war-torn America in this massive sequel to the million-selling series!, List(null, null, null, 187, null, null, null, null, null, null, null, null, null, null, null, null, null, 175, null, null, null, null, null, null, null, null, null, null, null, null, null, 200, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 209, null, null, null, null, null, null, null, null, null, null, null, 175, 123, null, null, null, null, null, null, null, 176, null, null, null, null, null, 119, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 208, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 175, null, null, null, 120, null, null, null, null, null, null, null, null, null, 184, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 163, 158, null, null, null, null, null, null, null, null, null, 213, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 157, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 182, 134, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 190, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 221, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, http://www.cookservedelicious.com)",1000030
"List(1000040, List(Single-player), 0, DoubleC Games, 0, Action, Casual, Indie, Simulation, https://cdn.akamai.steamstatic.com/steam/apps/1000040/header.jpg?t=1627033870, 199, Simplified Chinese, 细胞战争, 1, 0 .. 20,000, List(false, false, true), 0, 199, DoubleC Games, 2019/03/30, 0, 这是一款打击感十足的细胞主题游戏！操作简单但活下去却不简单，“你”作为侵入人体的细菌病毒，通过与细胞之间的战斗来获得基因变异点数和进入下一关的资格，每种细菌病毒都有独特的能力和攻击效果，你是否可以破坏五大器官并占领人体呢！？, List(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 22, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 22, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 21, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 20, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000040
"List(1000080, List(Multi-player, Single-player, Steam Achievements, Full controller support, Steam Trading Cards), 3, IndieLeague Studio, 60, Action, Adventure, Indie, RPG, https://cdn.akamai.steamstatic.com/steam/apps/1000080/header.jpg?t=1667062553, 1999, Simplified Chinese, English, Traditional Chinese, Japanese, Korean, Zengeon, 462, 100,000 .. 200,000, List(false, true, true), 1018, 799, 2P Games, 2019/06/24, 0, Zengeon is an anime infused Action RPG and Roguelite with a selection of unique characters and varying play-styles. Slaughter your way through demonic hordes and colossal bosses with hundreds of combination and skill possibilities!, List(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 138, 77, null, 111, null, null, 115, null, null, null, null, null, null, 84, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 31, null, null, null, null, null, null, null, null, null, null, null, 34, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 36, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 57, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 128, null, null, null, null, null, null, 30, null, null, null, null, null, null, null, null, null, 51, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 62, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 121, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 53, 67, null, null, null, null, null, null, null, null, null, null, null, null, null, 33, null, null, null, null, null, null, null, 46, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000080

In [0]:
df.printSchema()

root
 |-- data: struct (nullable = true)
 |    |-- appid: long (nullable = true)
 |    |-- categories: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- ccu: long (nullable = true)
 |    |-- developer: string (nullable = true)
 |    |-- discount: string (nullable = true)
 |    |-- genre: string (nullable = true)
 |    |-- header_image: string (nullable = true)
 |    |-- initialprice: string (nullable = true)
 |    |-- languages: string (nullable = true)
 |    |-- name: string (nullable = true)
 |    |-- negative: long (nullable = true)
 |    |-- owners: string (nullable = true)
 |    |-- platforms: struct (nullable = true)
 |    |    |-- linux: boolean (nullable = true)
 |    |    |-- mac: boolean (nullable = true)
 |    |    |-- windows: boolean (nullable = true)
 |    |-- positive: long (nullable = true)
 |    |-- price: string (nullable = true)
 |    |-- publisher: string (nullable = true)
 |    |-- release_date: string (nullable = true)
 |    |-- required_age: string (nullable = true)
 |    |-- short_description: string (nullable = true)
 |    |-- tags: struct (nullable = true)
 |    |    |-- 1980s: long (nullable = true)
 |    |    |-- 1990's: long (nullable = true)
 |    |    |-- 2.5D: long (nullable = true)
 |    |    |-- 2D: long (nullable = true)
 |    |    |-- 2D Fighter: long (nullable = true)
 |    |    |-- 2D Platformer: long (nullable = true)
 |    |    |-- 360 Video: long (nullable = true)
 |    |    |-- 3D: long (nullable = true)
 |    |    |-- 3D Fighter: long (nullable = true)
 |    |    |-- 3D Platformer: long (nullable = true)
 |    |    |-- 3D Vision: long (nullable = true)
 |    |    |-- 4 Player Local: long (nullable = true)
 |    |    |-- 4X: long (nullable = true)
 |    |    |-- 6DOF: long (nullable = true)
 |    |    |-- 8-bit Music: long (nullable = true)
 |    |    |-- ATV: long (nullable = true)
 |    |    |-- Abstract: long (nullable = true)
 |    |    |-- Action: long (nullable = true)
 |    |    |-- Action RPG: long (nullable = true)
 |    |    |-- Action RTS: long (nullable = true)
 |    |    |-- Action Roguelike: long (nullable = true)
 |    |    |-- Action-Adventure: long (nullable = true)
 |    |    |-- Addictive: long (nullable = true)
 |    |    |-- Adventure: long (nullable = true)
 |    |    |-- Agriculture: long (nullable = true)
 |    |    |-- Aliens: long (nullable = true)
 |    |    |-- Alternate History: long (nullable = true)
 |    |    |-- Ambient: long (nullable = true)
 |    |    |-- America: long (nullable = true)
 |    |    |-- Animation & Modeling: long (nullable = true)
 |    |    |-- Anime: long (nullable = true)
 |    |    |-- Arcade: long (nullable = true)
 |    |    |-- Archery: long (nullable = true)
 |    |    |-- Arena Shooter: long (nullable = true)
 |    |    |-- Artificial Intelligence: long (nullable = true)
 |    |    |-- Assassin: long (nullable = true)
 |    |    |-- Asymmetric VR: long (nullable = true)
 |    |    |-- Asynchronous Multiplayer: long (nullable = true)
 |    |    |-- Atmospheric: long (nullable = true)
 |    |    |-- Audio Production: long (nullable = true)
 |    |    |-- Auto Battler: long (nullable = true)
 |    |    |-- Automation: long (nullable = true)
 |    |    |-- Automobile Sim: long (nullable = true)
 |    |    |-- BMX: long (nullable = true)
 |    |    |-- Base-Building: long (nullable = true)
 |    |    |-- Baseball: long (nullable = true)
 |    |    |-- Based On A Novel: long (nullable = true)
 |    |    |-- Basketball: long (nullable = true)
 |    |    |-- Battle Royale: long (nullable = true)
 |    |    |-- Beat 'em up: long (nullable = true)
 |    |    |-- Beautiful: long (nullable = true)
 |    |    |-- Benchmark: long (nullable = true)
 |    |    |-- Bikes: long (nullable = true)
 |    |    |-- Blood: long (nullable = true)
 |    |    |-- Board Game: long (nullable = true)
 |    |    |-- Boss Rush: long (nullable = true)
 |    |    |-- Bowling: long (nullable = true)
 |    |    |-- Boxing: long (nullable = true)
 |    |    |-- Building: long (nullable = true)
 |    |    |-- Bullet Hell: long (nullable = true)
 |    |    |-- Bullet Time: long (nullable = true)
 |    |    |-- CRPG: long (nullable = true)
 |    |    |-- Capitalism: long (nullable = true)
 |    |    |-- Card Battler: long (nullable = true)
 |    |    |-- Card Game: long (nullable = true)
 |    |    |-- Cartoon: long (nullable = true)
 |    |    |-- Cartoony: long (nullable = true)
 |    |    |-- Casual: long (nullable = true)
 |    |    |-- Cats: long (nullable = true)
 |    |    |-- Character Action Game: long (nullable = true)
 |    |    |-- Character Customization: long (nullable = true)
 |    |    |-- Chess: long (nullable = true)
 |    |    |-- Choices Matter: long (nullable = true)
 |    |    |-- Choose Your Own Adventure: long (nullable = true)
 |    |    |-- Cinematic: long (nullable = true)
 |    |    |-- City Builder: long (nullable = true)
 |    |    |-- Class-Based: long (nullable = true)
 |    |    |-- Classic: long (nullable = true)
 |    |    |-- Clicker: long (nullable = true)
 |    |    |-- Co-op: long (nullable = true)
 |    |    |-- Co-op Campaign: long (nullable = true)
 |    |    |-- Coding: long (nullable = true)
 |    |    |-- Cold War: long (nullable = true)
 |    |    |-- Collectathon: long (nullable = true)
 |    |    |-- Colony Sim: long (nullable = true)
 |    |    |-- Colorful: long (nullable = true)
 |    |    |-- Combat: long (nullable = true)
 |    |    |-- Combat Racing: long (nullable = true)
 |    |    |-- Comedy: long (nullable = true)
 |    |    |-- Comic Book: long (nullable = true)
 |    |    |-- Competitive: long (nullable = true)
 |    |    |-- Conspiracy: long (nullable = true)
 |    |    |-- Controller: long (nullable = true)
 |    |    |-- Conversation: long (nullable = true)
 |    |    |-- Cooking: long (nullable = true)
 |    |    |-- Cozy: long (nullable = true)
 |    |    |-- Crafting: long (nullable = true)
 |    |    |-- Creature Collector: long (nullable = true)
 |    |    |-- Cricket: long (nullable = true)
 |    |    |-- Crime: long (nullable = true)
 |    |    |-- Crowdfunded: long (nullable = true)
 |    |    |-- Cult Classic: long (nullable = true)
 |    |    |-- Cute: long (nullable = true)
 |    |    |-- Cyberpunk: long (nullable = true)
 |    |    |-- Cycling: long (nullable = true)
 |    |    |-- Dark: long (nullable = true)
 |    |    |-- Dark Comedy: long (nullable = true)
 |    |    |-- Dark Fantasy: long (nullable = true)
 |    |    |-- Dark Humor: long (nullable = true)
 |    |    |-- Dating Sim: long (nullable = true)
 |    |    |-- Deckbuilding: long (nullable = true)
 |    |    |-- Demons: long (nullable = true)
 |    |    |-- Design & Illustration: long (nullable = true)
 |    |    |-- Destruction: long (nullable = true)
 |    |    |-- Detective: long (nullable = true)
 |    |    |-- Difficult: long (nullable = true)
 |    |    |-- Dinosaurs: long (nullable = true)
 |    |    |-- Diplomacy: long (nullable = true)
 |    |    |-- Documentary: long (nullable = true)
 |    |    |-- Dog: long (nullable = true)
 |    |    |-- Dragons: long (nullable = true)
 |    |    |-- Drama: long (nullable = true)
 |    |    |-- Driving: long (nullable = true)
 |    |    |-- Dungeon Crawler: long (nullable = true)
 |    |    |-- Dungeons & Dragons: long (nullable = true)
 |    |    |-- Dynamic Narration: long (nullable = true)
 |    |    |-- Dystopian : long (nullable = true)
 |    |    |-- Early Access: long (nullable = true)
 |    |    |-- Economy: long (nullable = true)
 |    |    |-- Education: long (nullable = true)
 |    |    |-- Electronic: long (nullable = true)
 |    |    |-- Electronic Music: long (nullable = true)
 |    |    |-- Emotional: long (nullable = true)
 |    |    |-- Epic: long (nullable = true)
 |    |    |-- Episodic: long (nullable = true)
 |    |    |-- Escape Room: long (nullable = true)
 |    |    |-- Experience: long (nullable = true)
 |    |    |-- Experimental: long (nullable = true)
 |    |    |-- Exploration: long (nullable = true)
 |    |    |-- FMV: long (nullable = true)
 |    |    |-- FPS: long (nullable = true)
 |    |    |-- Faith: long (nullable = true)
 |    |    |-- Family Friendly: long (nullable = true)
 |    |    |-- Fantasy: long (nullable = true)
 |    |    |-- Farming: long (nullable = true)
 |    |    |-- Farming Sim: long (nullable = true)
 |    |    |-- Fast-Paced: long (nullable = true)
 |    |    |-- Feature Film: long (nullable = true)
 |    |    |-- Female Protagonist: long (nullable = true)
 |    |    |-- Fighting: long (nullable = true)
 |    |    |-- First-Person: long (nullable = true)
 |    |    |-- Fishing: long (nullable = true)
 |    |    |-- Flight: long (nullable = true)
 |    |    |-- Football: long (nullable = true)
 |    |    |-- Foreign: long (nullable = true)
 |    |    |-- Free to Play: long (nullable = true)
 |    |    |-- Funny: long (nullable = true)
 |    |    |-- Futuristic: long (nullable = true)
 |    |    |-- Gambling: long (nullable = true)
 |    |    |-- Game Development: long (nullable = true)
 |    |    |-- GameMaker: long (nullable = true)
 |    |    |-- Games Workshop: long (nullable = true)
 |    |    |-- Gaming: long (nullable = true)
 |    |    |-- God Game: long (nullable = true)
 |    |    |-- Golf: long (nullable = true)
 |    |    |-- Gore: long (nullable = true)
 |    |    |-- Gothic: long (nullable = true)
 |    |    |-- Grand Strategy: long (nullable = true)
 |    |    |-- Great Soundtrack: long (nullable = true)
 |    |    |-- Grid-Based Movement: long (nullable = true)
 |    |    |-- Gun Customization: long (nullable = true)
 |    |    |-- Hack and Slash: long (nullable = true)
 |    |    |-- Hacking: long (nullable = true)
 |    |    |-- Hand-drawn: long (nullable = true)
 |    |    |-- Hardware: long (nullable = true)
 |    |    |-- Heist: long (nullable = true)
 |    |    |-- Hentai: long (nullable = true)
 |    |    |-- Hero Shooter: long (nullable = true)
 |    |    |-- Hex Grid: long (nullable = true)
 |    |    |-- Hidden Object: long (nullable = true)
 |    |    |-- Historical: long (nullable = true)
 |    |    |-- Hockey: long (nullable = true)
 |    |    |-- Horror: long (nullable = true)
 |    |    |-- Horses: long (nullable = true)
 |    |    |-- Hunting: long (nullable = true)
 |    |    |-- Idler: long (nullable = true)
 |    |    |-- Illuminati: long (nullable = true)
 |    |    |-- Immersive: long (nullable = true)
 |    |    |-- Immersive Sim: long (nullable = true)
 |    |    |-- Indie: long (nullable = true)
 |    |    |-- Instrumental Music: long (nullable = true)
 |    |    |-- Intentionally Awkward Controls: long (nullable = true)
 |    |    |-- Interactive Fiction: long (nullable = true)
 |    |    |-- Inventory Management: long (nullable = true)
 |    |    |-- Investigation: long (nullable = true)
 |    |    |-- Isometric: long (nullable = true)
 |    |    |-- JRPG: long (nullable = true)
 |    |    |-- Jet: long (nullable = true)
 |    |    |-- Job Simulator: long (nullable = true)
 |    |    |-- Jump Scare: long (nullable = true)
 |    |    |-- Kickstarter: long (nullable = true)
 |    |    |-- LEGO: long (nullable = true)
 |    |    |-- LGBTQ+: long (nullable = true)
 |    |    |-- Lemmings: long (nullable = true)
 |    |    |-- Level Editor: long (nullable = true)
 |    |    |-- Life Sim: long (nullable = true)
 |    |    |-- Linear: long (nullable = true)
 |    |    |-- Local Co-Op: long (nullable = true)
 |    |    |-- Local Multiplayer: long (nullable = true)
 |    |    |-- Logic: long (nullable = true)
 |    |    |-- Loot: long (nullable = true)
 |    |    |-- Looter Shooter: long (nullable = true)
 |    |    |-- Lore-Rich: long (nullable = true)
 |    |    |-- Lovecraftian: long (nullable = true)
 |    |    |-- MMORPG: long (nullable = true)
 |    |    |-- MOBA: long (nullable = true)
 |    |    |-- Magic: long (nullable = true)
 |    |    |-- Mahjong: long (nullable = true)
 |    |    |-- Management: long (nullable = true)
 |    |    |-- Mars: long (nullable = true)
 |    |    |-- Martial Arts: long (nullable = true)
 |    |    |-- Massively Multiplayer: long (nullable = true)
 |    |    |-- Masterpiece: long (nullable = true)
 |    |    |-- Match 3: long (nullable = true)
 |    |    |-- Mature: long (nullable = true)
 |    |    |-- Mechs: long (nullable = true)
 |    |    |-- Medical Sim: long (nullable = true)
 |    |    |-- Medieval: long (nullable = true)
 |    |    |-- Memes: long (nullable = true)
 |    |    |-- Metroidvania: long (nullable = true)
 |    |    |-- Military: long (nullable = true)
 |    |    |-- Mini Golf: long (nullable = true)
 |    |    |-- Minigames: long (nullable = true)
 |    |    |-- Minimalist: long (nullable = true)
 |    |    |-- Mining: long (nullable = true)
 |    |    |-- Mod: long (nullable = true)
 |    |    |-- Moddable: long (nullable = true)
 |    |    |-- Modern: long (nullable = true)
 |    |    |-- Motocross: long (nullable = true)
 |    |    |-- Motorbike: long (nullable = true)
 |    |    |-- Mouse only: long (nullable = true)
 |    |    |-- Movie: long (nullable = true)
 |    |    |-- Multiplayer: long (nullable = true)
 |    |    |-- Multiple Endings: long (nullable = true)
 |    |    |-- Music: long (nullable = true)
 |    |    |-- Music-Based Procedural Generation: long (nullable = true)
 |    |    |-- Musou: long (nullable = true)
 |    |    |-- Mystery: long (nullable = true)
 |    |    |-- Mystery Dungeon: long (nullable = true)
 |    |    |-- Mythology: long (nullable = true)
 |    |    |-- NSFW: long (nullable = true)
 |    |    |-- Narration: long (nullable = true)
 |    |    |-- Narrative: long (nullable = true)
 |    |    |-- Nature: long (nullable = true)
 |    |    |-- Naval: long (nullable = true)
 |    |    |-- Naval Combat: long (nullable = true)
 |    |    |-- Ninja: long (nullable = true)
 |    |    |-- Noir: long (nullable = true)
 |    |    |-- Nonlinear: long (nullable = true)
 |    |    |-- Nostalgia: long (nullable = true)
 |    |    |-- Nudity: long (nullable = true)
 |    |    |-- Offroad: long (nullable = true)
 |    |    |-- Old School: long (nullable = true)
 |    |    |-- On-Rails Shooter: long (nullable = true)
 |    |    |-- Online Co-Op: long (nullable = true)
 |    |    |-- Open World: long (nullable = true)
 |    |    |-- Open World Survival Craft: long (nullable = true)
 |    |    |-- Otome: long (nullable = true)
 |    |    |-- Outbreak Sim: long (nullable = true)
 |    |    |-- Parkour: long (nullable = true)
 |    |    |-- Parody : long (nullable = true)
 |    |    |-- Party: long (nullable = true)
 |    |    |-- Party Game: long (nullable = true)
 |    |    |-- Party-Based RPG: long (nullable = true)
 |    |    |-- Perma Death: long (nullable = true)
 |    |    |-- Philosophical: long (nullable = true)
 |    |    |-- Photo Editing: long (nullable = true)
 |    |    |-- Physics: long (nullable = true)
 |    |    |-- Pinball: long (nullable = true)
 |    |    |-- Pirates: long (nullable = true)
 |    |    |-- Pixel Graphics: long (nullable = true)
 |    |    |-- Platformer: long (nullable = true)
 |    |    |-- Point & Click: long (nullable = true)
 |    |    |-- Political: long (nullable = true)
 |    |    |-- Political Sim: long (nullable = true)
 |    |    |-- Politics: long (nullable = true)
 |    |    |-- Pool: long (nullable = true)
 |    |    |-- Post-apocalyptic: long (nullable = true)
 |    |    |-- Precision Platformer: long (nullable = true)
 |    |    |-- Procedural Generation: long (nullable = true)
 |    |    |-- Programming: long (nullable = true)
 |    |    |-- Psychedelic: long (nullable = true)
 |    |    |-- Psychological: long (nullable = true)
 |    |    |-- Psychological Horror: long (nullable = true)
 |    |    |-- Puzzle: long (nullable = true)
 |    |    |-- Puzzle-Platformer: long (nullable = true)
 |    |    |-- PvE: long (nullable = true)
 |    |    |-- PvP: long (nullable = true)
 |    |    |-- Quick-Time Events: long (nullable = true)
 |    |    |-- RPG: long (nullable = true)
 |    |    |-- RPGMaker: long (nullable = true)
 |    |    |-- RTS: long (nullable = true)
 |    |    |-- Racing: long (nullable = true)
 |    |    |-- Real Time Tactics: long (nullable = true)
 |    |    |-- Real-Time: long (nullable = true)
 |    |    |-- Real-Time with Pause: long (nullable = true)
 |    |    |-- Realistic: long (nullable = true)
 |    |    |-- Reboot: long (nullable = true)
 |    |    |-- Relaxing: long (nullable = true)
 |    |    |-- Remake: long (nullable = true)
 |    |    |-- Replay Value: long (nullable = true)
 |    |    |-- Resource Management: long (nullable = true)
 |    |    |-- Retro: long (nullable = true)
 |    |    |-- Rhythm: long (nullable = true)
 |    |    |-- Robots: long (nullable = true)
 |    |    |-- Rock Music: long (nullable = true)
 |    |    |-- Rogue-like: long (nullable = true)
 |    |    |-- Rogue-lite: long (nullable = true)
 |    |    |-- Roguelike Deckbuilder: long (nullable = true)
 |    |    |-- Roguevania: long (nullable = true)
 |    |    |-- Romance: long (nullable = true)
 |    |    |-- Rome: long (nullable = true)
 |    |    |-- Rugby: long (nullable = true)
 |    |    |-- Runner: long (nullable = true)
 |    |    |-- Sailing: long (nullable = true)
 |    |    |-- Sandbox: long (nullable = true)
 |    |    |-- Satire: long (nullable = true)
 |    |    |-- Sci-fi: long (nullable = true)
 |    |    |-- Science: long (nullable = true)
 |    |    |-- Score Attack: long (nullable = true)
 |    |    |-- Sequel: long (nullable = true)
 |    |    |-- Sexual Content: long (nullable = true)
 |    |    |-- Shoot 'Em Up: long (nullable = true)
 |    |    |-- Shooter: long (nullable = true)
 |    |    |-- Shop Keeper: long (nullable = true)
 |    |    |-- Short: long (nullable = true)
 |    |    |-- Side Scroller: long (nullable = true)
 |    |    |-- Silent Protagonist: long (nullable = true)
 |    |    |-- Simulation: long (nullable = true)
 |    |    |-- Singleplayer: long (nullable = true)
 |    |    |-- Skateboarding: long (nullable = true)
 |    |    |-- Skating: long (nullable = true)
 |    |    |-- Skiing: long (nullable = true)
 |    |    |-- Sniper: long (nullable = true)
 |    |    |-- Snooker: long (nullable = true)
 |    |    |-- Snow: long (nullable = true)
 |    |    |-- Snowboarding: long (nullable = true)
 |    |    |-- Soccer: long (nullable = true)
 |    |    |-- Social Deduction: long (nullable = true)
 |    |    |-- Software: long (nullable = true)
 |    |    |-- Software Training: long (nullable = true)
 |    |    |-- Sokoban: long (nullable = true)
 |    |    |-- Solitaire: long (nullable = true)
 |    |    |-- Souls-like: long (nullable = true)
 |    |    |-- Soundtrack: long (nullable = true)
 |    |    |-- Space: long (nullable = true)
 |    |    |-- Space Sim: long (nullable = true)
 |    |    |-- Spaceships: long (nullable = true)
 |    |    |-- Spectacle fighter: long (nullable = true)
 |    |    |-- Spelling: long (nullable = true)
 |    |    |-- Split Screen: long (nullable = true)
 |    |    |-- Sports: long (nullable = true)
 |    |    |-- Stealth: long (nullable = true)
 |    |    |-- Steam Machine: long (nullable = true)
 |    |    |-- Steampunk: long (nullable = true)
 |    |    |-- Story Rich: long (nullable = true)
 |    |    |-- Strategy: long (nullable = true)
 |    |    |-- Strategy RPG: long (nullable = true)
 |    |    |-- Stylized: long (nullable = true)
 |    |    |-- Submarine: long (nullable = true)
 |    |    |-- Superhero: long (nullable = true)
 |    |    |-- Supernatural: long (nullable = true)
 |    |    |-- Surreal: long (nullable = true)
 |    |    |-- Survival: long (nullable = true)
 |    |    |-- Survival Horror: long (nullable = true)
 |    |    |-- Swordplay: long (nullable = true)
 |    |    |-- Tabletop: long (nullable = true)
 |    |    |-- Tactical: long (nullable = true)
 |    |    |-- Tactical RPG: long (nullable = true)

In [0]:
df.count()

55691

In [0]:
display(df.limit(20))

data,id
"List(10, List(Multi-player, Valve Anti-Cheat enabled, Online PvP, Shared/Split Screen PvP, PvP), 13990, Valve, 0, Action, https://cdn.akamai.steamstatic.com/steam/apps/10/header.jpg?t=1666823513, 999, English, French, German, Italian, Spanish - Spain, Simplified Chinese, Traditional Chinese, Korean, Counter-Strike, 5199, 10,000,000 .. 20,000,000, List(true, true, true), 201215, 999, Valve, 2000/11/1, 0, Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role., List(266, 1191, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5426, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 227, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2784, null, null, null, null, null, null, null, null, null, null, null, null, 1607, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 4831, null, null, null, null, null, null, null, null, null, 1707, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 632, null, null, null, null, null, null, null, null, null, null, null, 3392, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 131, null, null, 769, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 881, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 289, null, null, null, 3353, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 614, null, null, null, null, null, null, 304, null, null, null, 1344, null, null, 1864, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1192), game, )",10
"List(1000000, List(Single-player, Partial Controller Support, Steam Achievements, Steam Cloud), 0, IndigoBlue Game Studio, 0, Action, Adventure, Indie, https://cdn.akamai.steamstatic.com/steam/apps/1000000/header.jpg?t=1655723048, 999, English, Korean, Simplified Chinese, ASCENXION, 5, 0 .. 20,000, List(false, false, true), 27, 999, PsychoFlux Entertainment, 2021/05/14, 0, ASCENXION is a 2D shoot 'em up game where you explore the field to progress. Players must overcome puzzles, traps, elite units, boss fights, and other various obstacles while navigating the field. Grow stronger through rewards earned, to uncover the truth of this world., List(null, null, null, 159, null, null, null, null, null, null, null, null, null, null, null, null, 111, 138, null, null, null, null, null, 73, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 88, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 179, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 124, null, null, null, null, null, null, 148, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 161, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 51, null, null, null, null, null, null, null, 38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 69, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 181, null, null, null, 136, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 100, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 186, 159, null, null, 175, null, null, 71, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 170, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000000
"List(1000010, List(Single-player, Partial Controller Support, Steam Achievements, Steam Cloud, Steam Trading Cards), 99, NEXT Studios, 70, Adventure, Indie, RPG, Strategy, https://cdn.akamai.steamstatic.com/steam/apps/1000010/header.jpg?t=1655724189, 1999, Simplified Chinese, English, Japanese, Traditional Chinese, French, German, Spanish - Spain, Russian, Portuguese - Brazil, Crown Trick, 646, 200,000 .. 500,000, List(false, false, true), 4032, 599, Team17, NEXT Studios, 2020/10/16, 0, Enter a labyrinth that moves as you move, where mastering the elements is key to defeating enemies and uncovering the mysteries of this underground world. With a new experience awaiting every time you enter the dungeon, let the power bestowed by the crown guide you in this challenging adventure!, List(null, null, null, 205, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 179, null, 225, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 189, null, null, null, null, null, null, null, 225, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 179, null, null, null, null, 217, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 171, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 231, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 237, null, null, null, null, null, null, null, null, null, null, 192, null, null, null, null, null, 268, 226, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 211, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 225, null, null, null, null, null, null, null, null, null, null, 184, null, null, null, null, null, null, null, null, null, null, null, null, null, 178, null, null, null, null, null, null, null, null, null, null, null, 222, 254, 216, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000010
"List(1000030, List(Multi-player, Single-player, Co-op, Steam Achievements, Steam Cloud, Shared/Split Screen, Full controller support, Steam Trading Cards, Shared/Split Screen Co-op, Remote Play on Phone, Remote Play on Tablet, Remote Play on TV, Remote Play Together), 76, Vertigo Gaming Inc., 0, Action, Indie, Simulation, Strategy, https://cdn.akamai.steamstatic.com/steam/apps/1000030/header.jpg?t=1660866300, 1999, English, Cook, Serve, Delicious! 3?!, 115, 100,000 .. 200,000, List(false, true, true), 1575, 1999, Vertigo Gaming Inc., 2020/10/14, 0, Cook, serve and manage your food truck as you dish out hundreds of different foods across war-torn America in this massive sequel to the million-selling series!, List(null, null, null, 187, null, null, null, null, null, null, null, null, null, null, null, null, null, 175, null, null, null, null, null, null, null, null, null, null, null, null, null, 200, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 209, null, null, null, null, null, null, null, null, null, null, null, 175, 123, null, null, null, null, null, null, null, 176, null, null, null, null, null, 119, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 208, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 175, null, null, null, 120, null, null, null, null, null, null, null, null, null, 184, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 163, 158, null, null, null, null, null, null, null, null, null, 213, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 157, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 182, 134, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 190, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 221, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, http://www.cookservedelicious.com)",1000030
"List(1000040, List(Single-player), 0, DoubleC Games, 0, Action, Casual, Indie, Simulation, https://cdn.akamai.steamstatic.com/steam/apps/1000040/header.jpg?t=1627033870, 199, Simplified Chinese, 细胞战争, 1, 0 .. 20,000, List(false, false, true), 0, 199, DoubleC Games, 2019/03/30, 0, 这是一款打击感十足的细胞主题游戏！操作简单但活下去却不简单，“你”作为侵入人体的细菌病毒，通过与细胞之间的战斗来获得基因变异点数和进入下一关的资格，每种细菌病毒都有独特的能力和攻击效果，你是否可以破坏五大器官并占领人体呢！？, List(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 22, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 22, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 21, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 20, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000040
"List(1000080, List(Multi-player, Single-player, Steam Achievements, Full controller support, Steam Trading Cards), 3, IndieLeague Studio, 60, Action, Adventure, Indie, RPG, https://cdn.akamai.steamstatic.com/steam/apps/1000080/header.jpg?t=1667062553, 1999, Simplified Chinese, English, Traditional Chinese, Japanese, Korean, Zengeon, 462, 100,000 .. 200,000, List(false, true, true), 1018, 799, 2P Games, 2019/06/24, 0, Zengeon is an anime infused Action RPG and Roguelite with a selection of unique characters and varying play-styles. Slaughter your way through demonic hordes and colossal bosses with hundreds of combination and skill possibilities!, List(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 138, 77, null, 111, null, null, 115, null, null, null, null, null, null, 84, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 31, null, null, null, null, null, null, null, null, null, null, null, 34, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 36, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 57, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 128, null, null, null, null, null, null, 30, null, null, null, null, null, null, null, null, null, 51, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 62, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 121, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 53, 67, null, null, null, null, null, null, null, null, null, null, null, null, null, 33, null, null, null, null, null, null, null, 46, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), game, )",1000080

### 1.2 Flatten du champ "data"

Les données sont contenues dans une structure "data". Nous aplatissons donc le dataframe en extrayant toutes les données de "Data" et en supprimant ce niveau.

In [0]:
# Flattening the DataFrame
df = df.select("*", "data.*").drop("data")
# print the schema of the flattened DataFrame
df.printSchema()

root
 |-- id: string (nullable = true)
 |-- appid: long (nullable = true)
 |-- categories: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- ccu: long (nullable = true)
 |-- developer: string (nullable = true)
 |-- discount: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- header_image: string (nullable = true)
 |-- initialprice: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- negative: long (nullable = true)
 |-- owners: string (nullable = true)
 |-- platforms: struct (nullable = true)
 |    |-- linux: boolean (nullable = true)
 |    |-- mac: boolean (nullable = true)
 |    |-- windows: boolean (nullable = true)
 |-- positive: long (nullable = true)
 |-- price: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- release_date: string (nullable = true)
 |-- required_age: string (nullable = true)
 |-- short_description: string (nullable = true)
 |-- tags: struct (nullable = true)
 |    |-- 1980s: long (nullable = true)
 |    |-- 1990's: long (nullable = true)
 |    |-- 2.5D: long (nullable = true)
 |    |-- 2D: long (nullable = true)
 |    |-- 2D Fighter: long (nullable = true)
 |    |-- 2D Platformer: long (nullable = true)
 |    |-- 360 Video: long (nullable = true)
 |    |-- 3D: long (nullable = true)
 |    |-- 3D Fighter: long (nullable = true)
 |    |-- 3D Platformer: long (nullable = true)
 |    |-- 3D Vision: long (nullable = true)
 |    |-- 4 Player Local: long (nullable = true)
 |    |-- 4X: long (nullable = true)
 |    |-- 6DOF: long (nullable = true)
 |    |-- 8-bit Music: long (nullable = true)
 |    |-- ATV: long (nullable = true)
 |    |-- Abstract: long (nullable = true)
 |    |-- Action: long (nullable = true)
 |    |-- Action RPG: long (nullable = true)
 |    |-- Action RTS: long (nullable = true)
 |    |-- Action Roguelike: long (nullable = true)
 |    |-- Action-Adventure: long (nullable = true)
 |    |-- Addictive: long (nullable = true)
 |    |-- Adventure: long (nullable = true)
 |    |-- Agriculture: long (nullable = true)
 |    |-- Aliens: long (nullable = true)
 |    |-- Alternate History: long (nullable = true)
 |    |-- Ambient: long (nullable = true)
 |    |-- America: long (nullable = true)
 |    |-- Animation & Modeling: long (nullable = true)
 |    |-- Anime: long (nullable = true)
 |    |-- Arcade: long (nullable = true)
 |    |-- Archery: long (nullable = true)
 |    |-- Arena Shooter: long (nullable = true)
 |    |-- Artificial Intelligence: long (nullable = true)
 |    |-- Assassin: long (nullable = true)
 |    |-- Asymmetric VR: long (nullable = true)
 |    |-- Asynchronous Multiplayer: long (nullable = true)
 |    |-- Atmospheric: long (nullable = true)
 |    |-- Audio Production: long (nullable = true)
 |    |-- Auto Battler: long (nullable = true)
 |    |-- Automation: long (nullable = true)
 |    |-- Automobile Sim: long (nullable = true)
 |    |-- BMX: long (nullable = true)
 |    |-- Base-Building: long (nullable = true)
 |    |-- Baseball: long (nullable = true)
 |    |-- Based On A Novel: long (nullable = true)
 |    |-- Basketball: long (nullable = true)
 |    |-- Battle Royale: long (nullable = true)
 |    |-- Beat 'em up: long (nullable = true)
 |    |-- Beautiful: long (nullable = true)
 |    |-- Benchmark: long (nullable = true)
 |    |-- Bikes: long (nullable = true)
 |    |-- Blood: long (nullable = true)
 |    |-- Board Game: long (nullable = true)
 |    |-- Boss Rush: long (nullable = true)
 |    |-- Bowling: long (nullable = true)
 |    |-- Boxing: long (nullable = true)
 |    |-- Building: long (nullable = true)
 |    |-- Bullet Hell: long (nullable = true)
 |    |-- Bullet Time: long (nullable = true)
 |    |-- CRPG: long (nullable = true)
 |    |-- Capitalism: long (nullable = true)
 |    |-- Card Battler: long (nullable = true)
 |    |-- Card Game: long (nullable = true)
 |    |-- Cartoon: long (nullable = true)
 |    |-- Cartoony: long (nullable = true)
 |    |-- Casual: long (nullable = true)
 |    |-- Cats: long (nullable = true)
 |    |-- Character Action Game: long (nullable = true)
 |    |-- Character Customization: long (nullable = true)
 |    |-- Chess: long (nullable = true)
 |    |-- Choices Matter: long (nullable = true)
 |    |-- Choose Your Own Adventure: long (nullable = true)
 |    |-- Cinematic: long (nullable = true)
 |    |-- City Builder: long (nullable = true)
 |    |-- Class-Based: long (nullable = true)
 |    |-- Classic: long (nullable = true)
 |    |-- Clicker: long (nullable = true)
 |    |-- Co-op: long (nullable = true)
 |    |-- Co-op Campaign: long (nullable = true)
 |    |-- Coding: long (nullable = true)
 |    |-- Cold War: long (nullable = true)
 |    |-- Collectathon: long (nullable = true)
 |    |-- Colony Sim: long (nullable = true)
 |    |-- Colorful: long (nullable = true)
 |    |-- Combat: long (nullable = true)
 |    |-- Combat Racing: long (nullable = true)
 |    |-- Comedy: long (nullable = true)
 |    |-- Comic Book: long (nullable = true)
 |    |-- Competitive: long (nullable = true)
 |    |-- Conspiracy: long (nullable = true)
 |    |-- Controller: long (nullable = true)
 |    |-- Conversation: long (nullable = true)
 |    |-- Cooking: long (nullable = true)
 |    |-- Cozy: long (nullable = true)
 |    |-- Crafting: long (nullable = true)
 |    |-- Creature Collector: long (nullable = true)
 |    |-- Cricket: long (nullable = true)
 |    |-- Crime: long (nullable = true)
 |    |-- Crowdfunded: long (nullable = true)
 |    |-- Cult Classic: long (nullable = true)
 |    |-- Cute: long (nullable = true)
 |    |-- Cyberpunk: long (nullable = true)
 |    |-- Cycling: long (nullable = true)
 |    |-- Dark: long (nullable = true)
 |    |-- Dark Comedy: long (nullable = true)
 |    |-- Dark Fantasy: long (nullable = true)
 |    |-- Dark Humor: long (nullable = true)
 |    |-- Dating Sim: long (nullable = true)
 |    |-- Deckbuilding: long (nullable = true)
 |    |-- Demons: long (nullable = true)
 |    |-- Design & Illustration: long (nullable = true)
 |    |-- Destruction: long (nullable = true)
 |    |-- Detective: long (nullable = true)
 |    |-- Difficult: long (nullable = true)
 |    |-- Dinosaurs: long (nullable = true)
 |    |-- Diplomacy: long (nullable = true)
 |    |-- Documentary: long (nullable = true)
 |    |-- Dog: long (nullable = true)
 |    |-- Dragons: long (nullable = true)
 |    |-- Drama: long (nullable = true)
 |    |-- Driving: long (nullable = true)
 |    |-- Dungeon Crawler: long (nullable = true)
 |    |-- Dungeons & Dragons: long (nullable = true)
 |    |-- Dynamic Narration: long (nullable = true)
 |    |-- Dystopian : long (nullable = true)
 |    |-- Early Access: long (nullable = true)
 |    |-- Economy: long (nullable = true)
 |    |-- Education: long (nullable = true)
 |    |-- Electronic: long (nullable = true)
 |    |-- Electronic Music: long (nullable = true)
 |    |-- Emotional: long (nullable = true)
 |    |-- Epic: long (nullable = true)
 |    |-- Episodic: long (nullable = true)
 |    |-- Escape Room: long (nullable = true)
 |    |-- Experience: long (nullable = true)
 |    |-- Experimental: long (nullable = true)
 |    |-- Exploration: long (nullable = true)
 |    |-- FMV: long (nullable = true)
 |    |-- FPS: long (nullable = true)
 |    |-- Faith: long (nullable = true)
 |    |-- Family Friendly: long (nullable = true)
 |    |-- Fantasy: long (nullable = true)
 |    |-- Farming: long (nullable = true)
 |    |-- Farming Sim: long (nullable = true)
 |    |-- Fast-Paced: long (nullable = true)
 |    |-- Feature Film: long (nullable = true)
 |    |-- Female Protagonist: long (nullable = true)
 |    |-- Fighting: long (nullable = true)
 |    |-- First-Person: long (nullable = true)
 |    |-- Fishing: long (nullable = true)
 |    |-- Flight: long (nullable = true)
 |    |-- Football: long (nullable = true)
 |    |-- Foreign: long (nullable = true)
 |    |-- Free to Play: long (nullable = true)
 |    |-- Funny: long (nullable = true)
 |    |-- Futuristic: long (nullable = true)
 |    |-- Gambling: long (nullable = true)
 |    |-- Game Development: long (nullable = true)
 |    |-- GameMaker: long (nullable = true)
 |    |-- Games Workshop: long (nullable = true)
 |    |-- Gaming: long (nullable = true)
 |    |-- God Game: long (nullable = true)
 |    |-- Golf: long (nullable = true)
 |    |-- Gore: long (nullable = true)
 |    |-- Gothic: long (nullable = true)
 |    |-- Grand Strategy: long (nullable = true)
 |    |-- Great Soundtrack: long (nullable = true)
 |    |-- Grid-Based Movement: long (nullable = true)
 |    |-- Gun Customization: long (nullable = true)
 |    |-- Hack and Slash: long (nullable = true)
 |    |-- Hacking: long (nullable = true)
 |    |-- Hand-drawn: long (nullable = true)
 |    |-- Hardware: long (nullable = true)
 |    |-- Heist: long (nullable = true)
 |    |-- Hentai: long (nullable = true)
 |    |-- Hero Shooter: long (nullable = true)
 |    |-- Hex Grid: long (nullable = true)
 |    |-- Hidden Object: long (nullable = true)
 |    |-- Historical: long (nullable = true)
 |    |-- Hockey: long (nullable = true)
 |    |-- Horror: long (nullable = true)
 |    |-- Horses: long (nullable = true)
 |    |-- Hunting: long (nullable = true)
 |    |-- Idler: long (nullable = true)
 |    |-- Illuminati: long (nullable = true)
 |    |-- Immersive: long (nullable = true)
 |    |-- Immersive Sim: long (nullable = true)
 |    |-- Indie: long (nullable = true)
 |    |-- Instrumental Music: long (nullable = true)
 |    |-- Intentionally Awkward Controls: long (nullable = true)
 |    |-- Interactive Fiction: long (nullable = true)
 |    |-- Inventory Management: long (nullable = true)
 |    |-- Investigation: long (nullable = true)
 |    |-- Isometric: long (nullable = true)
 |    |-- JRPG: long (nullable = true)
 |    |-- Jet: long (nullable = true)
 |    |-- Job Simulator: long (nullable = true)
 |    |-- Jump Scare: long (nullable = true)
 |    |-- Kickstarter: long (nullable = true)
 |    |-- LEGO: long (nullable = true)
 |    |-- LGBTQ+: long (nullable = true)
 |    |-- Lemmings: long (nullable = true)
 |    |-- Level Editor: long (nullable = true)
 |    |-- Life Sim: long (nullable = true)
 |    |-- Linear: long (nullable = true)
 |    |-- Local Co-Op: long (nullable = true)
 |    |-- Local Multiplayer: long (nullable = true)
 |    |-- Logic: long (nullable = true)
 |    |-- Loot: long (nullable = true)
 |    |-- Looter Shooter: long (nullable = true)
 |    |-- Lore-Rich: long (nullable = true)
 |    |-- Lovecraftian: long (nullable = true)
 |    |-- MMORPG: long (nullable = true)
 |    |-- MOBA: long (nullable = true)
 |    |-- Magic: long (nullable = true)
 |    |-- Mahjong: long (nullable = true)
 |    |-- Management: long (nullable = true)
 |    |-- Mars: long (nullable = true)
 |    |-- Martial Arts: long (nullable = true)
 |    |-- Massively Multiplayer: long (nullable = true)
 |    |-- Masterpiece: long (nullable = true)
 |    |-- Match 3: long (nullable = true)
 |    |-- Mature: long (nullable = true)
 |    |-- Mechs: long (nullable = true)
 |    |-- Medical Sim: long (nullable = true)
 |    |-- Medieval: long (nullable = true)
 |    |-- Memes: long (nullable = true)
 |    |-- Metroidvania: long (nullable = true)
 |    |-- Military: long (nullable = true)
 |    |-- Mini Golf: long (nullable = true)
 |    |-- Minigames: long (nullable = true)
 |    |-- Minimalist: long (nullable = true)
 |    |-- Mining: long (nullable = true)
 |    |-- Mod: long (nullable = true)
 |    |-- Moddable: long (nullable = true)
 |    |-- Modern: long (nullable = true)
 |    |-- Motocross: long (nullable = true)
 |    |-- Motorbike: long (nullable = true)
 |    |-- Mouse only: long (nullable = true)
 |    |-- Movie: long (nullable = true)
 |    |-- Multiplayer: long (nullable = true)
 |    |-- Multiple Endings: long (nullable = true)
 |    |-- Music: long (nullable = true)
 |    |-- Music-Based Procedural Generation: long (nullable = true)
 |    |-- Musou: long (nullable = true)
 |    |-- Mystery: long (nullable = true)
 |    |-- Mystery Dungeon: long (nullable = true)
 |    |-- Mythology: long (nullable = true)
 |    |-- NSFW: long (nullable = true)
 |    |-- Narration: long (nullable = true)
 |    |-- Narrative: long (nullable = true)
 |    |-- Nature: long (nullable = true)
 |    |-- Naval: long (nullable = true)
 |    |-- Naval Combat: long (nullable = true)
 |    |-- Ninja: long (nullable = true)
 |    |-- Noir: long (nullable = true)
 |    |-- Nonlinear: long (nullable = true)
 |    |-- Nostalgia: long (nullable = true)
 |    |-- Nudity: long (nullable = true)
 |    |-- Offroad: long (nullable = true)
 |    |-- Old School: long (nullable = true)
 |    |-- On-Rails Shooter: long (nullable = true)
 |    |-- Online Co-Op: long (nullable = true)
 |    |-- Open World: long (nullable = true)
 |    |-- Open World Survival Craft: long (nullable = true)
 |    |-- Otome: long (nullable = true)
 |    |-- Outbreak Sim: long (nullable = true)
 |    |-- Parkour: long (nullable = true)
 |    |-- Parody : long (nullable = true)
 |    |-- Party: long (nullable = true)
 |    |-- Party Game: long (nullable = true)
 |    |-- Party-Based RPG: long (nullable = true)
 |    |-- Perma Death: long (nullable = true)
 |    |-- Philosophical: long (nullable = true)
 |    |-- Photo Editing: long (nullable = true)
 |    |-- Physics: long (nullable = true)
 |    |-- Pinball: long (nullable = true)
 |    |-- Pirates: long (nullable = true)
 |    |-- Pixel Graphics: long (nullable = true)
 |    |-- Platformer: long (nullable = true)
 |    |-- Point & Click: long (nullable = true)
 |    |-- Political: long (nullable = true)
 |    |-- Political Sim: long (nullable = true)
 |    |-- Politics: long (nullable = true)
 |    |-- Pool: long (nullable = true)
 |    |-- Post-apocalyptic: long (nullable = true)
 |    |-- Precision Platformer: long (nullable = true)
 |    |-- Procedural Generation: long (nullable = true)
 |    |-- Programming: long (nullable = true)
 |    |-- Psychedelic: long (nullable = true)
 |    |-- Psychological: long (nullable = true)
 |    |-- Psychological Horror: long (nullable = true)
 |    |-- Puzzle: long (nullable = true)
 |    |-- Puzzle-Platformer: long (nullable = true)
 |    |-- PvE: long (nullable = true)
 |    |-- PvP: long (nullable = true)
 |    |-- Quick-Time Events: long (nullable = true)
 |    |-- RPG: long (nullable = true)
 |    |-- RPGMaker: long (nullable = true)
 |    |-- RTS: long (nullable = true)
 |    |-- Racing: long (nullable = true)
 |    |-- Real Time Tactics: long (nullable = true)
 |    |-- Real-Time: long (nullable = true)
 |    |-- Real-Time with Pause: long (nullable = true)
 |    |-- Realistic: long (nullable = true)
 |    |-- Reboot: long (nullable = true)
 |    |-- Relaxing: long (nullable = true)
 |    |-- Remake: long (nullable = true)
 |    |-- Replay Value: long (nullable = true)
 |    |-- Resource Management: long (nullable = true)
 |    |-- Retro: long (nullable = true)
 |    |-- Rhythm: long (nullable = true)
 |    |-- Robots: long (nullable = true)
 |    |-- Rock Music: long (nullable = true)
 |    |-- Rogue-like: long (nullable = true)
 |    |-- Rogue-lite: long (nullable = true)
 |    |-- Roguelike Deckbuilder: long (nullable = true)
 |    |-- Roguevania: long (nullable = true)
 |    |-- Romance: long (nullable = true)
 |    |-- Rome: long (nullable = true)
 |    |-- Rugby: long (nullable = true)
 |    |-- Runner: long (nullable = true)
 |    |-- Sailing: long (nullable = true)
 |    |-- Sandbox: long (nullable = true)
 |    |-- Satire: long (nullable = true)
 |    |-- Sci-fi: long (nullable = true)
 |    |-- Science: long (nullable = true)
 |    |-- Score Attack: long (nullable = true)
 |    |-- Sequel: long (nullable = true)
 |    |-- Sexual Content: long (nullable = true)
 |    |-- Shoot 'Em Up: long (nullable = true)
 |    |-- Shooter: long (nullable = true)
 |    |-- Shop Keeper: long (nullable = true)
 |    |-- Short: long (nullable = true)
 |    |-- Side Scroller: long (nullable = true)
 |    |-- Silent Protagonist: long (nullable = true)
 |    |-- Simulation: long (nullable = true)
 |    |-- Singleplayer: long (nullable = true)
 |    |-- Skateboarding: long (nullable = true)
 |    |-- Skating: long (nullable = true)
 |    |-- Skiing: long (nullable = true)
 |    |-- Sniper: long (nullable = true)
 |    |-- Snooker: long (nullable = true)
 |    |-- Snow: long (nullable = true)
 |    |-- Snowboarding: long (nullable = true)
 |    |-- Soccer: long (nullable = true)
 |    |-- Social Deduction: long (nullable = true)
 |    |-- Software: long (nullable = true)
 |    |-- Software Training: long (nullable = true)
 |    |-- Sokoban: long (nullable = true)
 |    |-- Solitaire: long (nullable = true)
 |    |-- Souls-like: long (nullable = true)
 |    |-- Soundtrack: long (nullable = true)
 |    |-- Space: long (nullable = true)
 |    |-- Space Sim: long (nullable = true)
 |    |-- Spaceships: long (nullable = true)
 |    |-- Spectacle fighter: long (nullable = true)
 |    |-- Spelling: long (nullable = true)
 |    |-- Split Screen: long (nullable = true)
 |    |-- Sports: long (nullable = true)
 |    |-- Stealth: long (nullable = true)
 |    |-- Steam Machine: long (nullable = true)
 |    |-- Steampunk: long (nullable = true)
 |    |-- Story Rich: long (nullable = true)
 |    |-- Strategy: long (nullable = true)
 |    |-- Strategy RPG: long (nullable = true)
 |    |-- Stylized: long (nullable = true)
 |    |-- Submarine: long (nullable = true)
 |    |-- Superhero: long (nullable = true)
 |    |-- Supernatural: long (nullable = true)
 |    |-- Surreal: long (nullable = true)
 |    |-- Survival: long (nullable = true)
 |    |-- Survival Horror: long (nullable = true)
 |    |-- Swordplay: long (nullable = true)
 |    |-- Tabletop: long (nullable = true)
 |    |-- Tactical: long (nullable = true)
 |    |-- Tactical RPG: long (nullable = true)
 |    |-- Tanks: long (nullable = true)
 |    |-- Team-Based: long (nullable = true)
 |    |-- Tennis: long (nullable = true)
 |    |-- Text-Based: long (nullable = true)
 |    |-- Third Person: long (nullable = true)
 |    |-- Third-Person Shooter: long (nullable = true)
 |    |-- Thriller: long (nullable = true)
 |    |-- Tile-Matching: long (nullable = true)
 |    |-- Time Attack: long (nullable = true)
 |    |-- Time Management: long (nullable = true)
 |    |-- Time Manipulation: long (nullable = true)
 |    |-- Time Travel: long (nullable = true)
 |    |-- Top-Down: long (nullable = true)
 |    |-- Top-Down Shooter: long (nullable = true)
 |    |-- Touch-Friendly: long (nullable = true)
 |    |-- Tower Defense: long (nullable = true)
 |    |-- TrackIR: long (nullable = true)
 |    |-- Trading: long (nullable = true)
 |    |-- Trading Card Game: long (nullable = true)
 |    |-- Traditional Roguelike: long (nullable = true)
 |    |-- Trains: long (nullable = true)
 |    |-- Transhumanism: long (nullable = true)
 |    |-- Transportation: long (nullable = true)
 |    |-- Trivia: long (nullable = true)
 |    |-- Turn-Based: long (nullable = true)
 |    |-- Turn-Based Combat: long (nullable = true)
 |    |-- Turn-Based Strategy: long (nullable = true)
 |    |-- Turn-Based Tactics: long (nullable = true)
 |    |-- Tutorial: long (nullable = true)
 |    |-- Twin Stick Shooter: long (nullable = true)
 |    |-- Typing: long (nullable = true)
 |    |-- Underground: long (nullable = true)
 |    |-- Underwater: long (nullable = true)
 |    |-- Unforgiving: long (nullable = true)
 |    |-- Utilities: long (nullable = true)
 |    |-- VR: long (nullable = true)
 |    |-- VR Only: long (nullable = true)
 |    |-- Vampire: long (nullable = true)
 |    |-- Vehicular Combat: long (nullable = true)
 |    |-- Video Production: long (nullable = true)
 |    |-- Vikings: long (nullable = true)
 |    |-- Villain Protagonist: long (nullable = true)
 |    |-- Violent: long (nullable = true)

In [0]:
pd.set_option('display.max_columns', None)
df.limit(5).toPandas()

,id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website
0,10,10,"[Multi-player, Valve Anti-Cheat enabled, Onlin...",13990,Valve,0,Action,https://cdn.akamai.steamstatic.com/steam/apps/...,999,"English, French, German, Italian, Spanish - Sp...",Counter-Strike,5199,"10,000,000 .. 20,000,000","{'linux': True, 'mac': True, 'windows': True}",201215,999,Valve,2000/11/1,0,Play the world's number 1 online action game. ...,"{'1980s': 266.0, '1990's': 1191.0, '2.5D': Non...",game,
1,1000000,1000000,"[Single-player, Partial Controller Support, St...",0,IndigoBlue Game Studio,0,"Action, Adventure, Indie",https://cdn.akamai.steamstatic.com/steam/apps/...,999,"English, Korean, Simplified Chinese",ASCENXION,5,"0 .. 20,000","{'linux': False, 'mac': False, 'windows': True}",27,999,PsychoFlux Entertainment,2021/05/14,0,ASCENXION is a 2D shoot 'em up game where you ...,"{'1980s': None, '1990's': None, '2.5D': None, ...",game,
2,1000010,1000010,"[Single-player, Partial Controller Support, St...",99,NEXT Studios,70,"Adventure, Indie, RPG, Strategy",https://cdn.akamai.steamstatic.com/steam/apps/...,1999,"Simplified Chinese, English, Japanese, Traditi...",Crown Trick,646,"200,000 .. 500,000","{'linux': False, 'mac': False, 'windows': True}",4032,599,"Team17, NEXT Studios",2020/10/16,0,"Enter a labyrinth that moves as you move, wher...","{'1980s': None, '1990's': None, '2.5D': None, ...",game,
3,1000030,1000030,"[Multi-player, Single-player, Co-op, Steam Ach...",76,Vertigo Gaming Inc.,0,"Action, Indie, Simulation, Strategy",https://cdn.akamai.steamstatic.com/steam/apps/...,1999,English,"Cook, Serve, Delicious! 3?!",115,"100,000 .. 200,000","{'linux': False, 'mac': True, 'windows': True}",1575,1999,Vertigo Gaming Inc.,2020/10/14,0,"Cook, serve and manage your food truck as you ...","{'1980s': None, '1990's': None, '2.5D': None, ...",game,http://www.cookservedelicious.com
4,1000040,1000040,[Single-player],0,DoubleC Games,0,"Action, Casual, Indie, Simulation",https://cdn.akamai.steamstatic.com/steam/apps/...,199,Simplified Chinese,细胞战争,1,"0 .. 20,000","{'linux': False, 'mac': False, 'windows': True}",0,199,DoubleC Games,2019/03/30,0,这是一款打击感十足的细胞主题游戏！操作简单但活下去却不简单，“你”作为侵入人体的细菌病毒，通...,"{'1980s': None, '1990's': None, '2.5D': None, ...",game,

In [0]:
df.describe().toPandas()

,summary,id,appid,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,positive,price,publisher,release_date,required_age,short_description,type,website
0,count,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691,55691
1,mean,1025603.0926720655,1025603.0926720655,138.9596164550825,67391.3,2.603777989262179,None,None,797.5663033524268,None,Infinity,241.8376937027527,None,1470.8755992889335,773.2849832109317,2498.75,None,0.1978882344490734,None,None,None
2,stddev,522784.9683283426,522784.9683283426,6002.067909130785,210681.95381245477,12.887080174743156,None,None,1104.7624778413053,None,NaN,5765.4137615598665,None,30982.733479535047,1093.134582723431,1809.1987867561706,None,2.296292461481821,None,None,None
3,min,10,10,0,,0,,https://cdn.akamai.steamstatic.com/steam/apps/...,0,,Fieldrunners 2,0,"0 .. 20,000",0,0,,,0,,game,
4,max,999990,2190950,874053,＼上／,90,Web Publishing,https://cdn.akamai.steamstatic.com/steam/apps/...,9999,Turkish,～Daydream～蝶が舞う頃に,908515,"500,000 .. 1,000,000",5943345,9999,Ｌｅｍｏｎ Ｂａｌｍ,2022/11/7,MA 15+,🚗 Take part in a roller coaster of emotions wi...,hardware,www.windybeard.com

### 1.3 Nettoyage et création des variables _dérivées_

Exploration de la colonne "type".

In [0]:
type_counts_df = df.groupBy("type").count().toPandas()
display(type_counts_df)

type,count
hardware,1
game,55690

Il s'avère que cette colonne contient de modalités : "hardware" qui n'a qu'une occurence et "game" qui concerne toutes les autres lignes.

Nous souhaitons comprendre ce qu'est "hardware"

In [0]:
hardware_df = df.filter(F.col('type') == 'hardware').toPandas()
display(hardware_df)

id,appid,categories,ccu,developer,discount,genre,header_image,initialprice,languages,name,negative,owners,platforms,positive,price,publisher,release_date,required_age,short_description,tags,type,website
353380,353380,"List(Full controller support, Remote Play Together)",0,,0,,https://cdn.akamai.steamstatic.com/steam/apps/353380/header.jpg?t=1617990330,0,,Steam Link,1771,"500,000 .. 1,000,000","List(true, true, true)",5803,0,Anima Locus,2015/11/10,0,"Extend your Steam gaming experience to your mobile device, TV, or another PC - all you need is a local network or internet connection. In addition, the Steam Link app now supports Remote Play Together. Now you can join games hosted on a friend’s PC just by clicking a link.","List(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 10, null, 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 5, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 11, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 15, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 6, null, null, null, null, null, null, null, null, null, 10, null, 16, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 23, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 39, null, null, null, null, null, null, null, null, null, null, null, null, null, 440, null, null, null, null, null, null, null, null, null, 11, 17, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)",hardware,https://store.steampowered.com/remoteplay

la modalité "hardware" concerne donc le Steam link, un accessoire de streaming sans fil vers un écran déporté. cela n'intéresse pas notre travail dans le cadre de ce projet. nous pouvons supprimer la modalité "hardware".

In [0]:
df = df.filter(F.col('type') != 'hardware')
df_copy=df.groupBy("type").count().toPandas()
display(df_copy)

type,count
game,55690

#### 1.4 Nettoyage des types des colonnes et ajout de variables

In [0]:

#initialprice
df = df.withColumn(
    "initialprice_eur",
    F.col("initialprice").cast("double") / 100
)

#price
df = df.withColumn(
    "price_eur",
    F.col("price").cast("double") / 100
)

#required_age
df = df.withColumn(
    "required_age_num",
    F.regexp_extract(F.col("required_age"), r"\d+", 0).cast("int")
)

#jeux adultes
df = df.withColumn(
    "is_adult_game",
    F.col("required_age_num") >= 18
)

#owners : c'est initialement un intervalle du nombre min et max de personnes possédant le jeu. On commence par nettoyer la colonne puis on calcul un nombre moyen de propriétaires (min+max)/2.
df = (df
    .withColumn("owners_clean", F.regexp_replace(F.col("owners"), r"\s", ""))
    .withColumn("owners_min",   F.regexp_extract(F.col("owners_clean"), r"^([\d,]+)\.\.", 1))
    .withColumn("owners_max",   F.regexp_extract(F.col("owners_clean"), r"\.\.([\d,]+)$", 1))
    .withColumn("owners_min",   F.regexp_replace(F.col("owners_min"), r",", "").cast("long"))
    .withColumn("owners_max",   F.regexp_replace(F.col("owners_max"), r",", "").cast("long"))
    .withColumn("owners_avg",   F.when(F.col("owners_min").isNotNull() & F.col("owners_max").isNotNull(),((F.col("owners_min") + F.col("owners_max"))/2).cast("double")))
)

#release_date
df = (
    df.withColumn(
        "release_date_dt",
        F.coalesce(
            F.try_to_date("release_date", "MMM d, yyyy"),
            F.try_to_date("release_date", "MMM dd, yyyy"),
            F.try_to_date("release_date", "yyyy-MM-dd"),
            F.try_to_date("release_date", "yyyy/M/d"),
            F.try_to_date("release_date", "yyyy/MM/dd"),

            # format yyyy/MM -> on ajoute /01
            F.try_to_date(F.concat(F.col("release_date"), F.lit("/01")), "yyyy/MM/dd")
        )
    )
    .withColumn("release_year", F.year("release_date_dt"))
    .withColumn("release_month", F.month("release_date_dt"))
)
#reviews : ajout d'un ratio d'avis positifs et d'un score
df = (df
    .withColumn("reviews_total", (F.coalesce(F.col("positive"), F.lit(0)) + F.coalesce(F.col("negative"), F.lit(0))).cast("long"))
    .withColumn(
        "pos_ratio",
        F.when(F.col("reviews_total") > 0, (F.col("positive") / F.col("reviews_total")).cast("double"))
    )
    .withColumn(
        "steam_score",
        F.when(F.col("reviews_total") > 0, (F.col("pos_ratio") * 100).cast("double"))
    )
)

# 2. Création des dataframes auxiliaires

### 2.1 table des tags

In [0]:
tags_fields = df.schema["tags"].dataType.names
print(len(tags_fields))
print(tags_fields[:20])

441
['1980s', "1990's", '2.5D', '2D', '2D Fighter', '2D Platformer', '360 Video', '3D', '3D Fighter', '3D Platformer', '3D Vision', '4 Player Local', '4X', '6DOF', '8-bit Music', 'ATV', 'Abstract', 'Action', 'Action RPG', 'Action RTS']

In [0]:
tags_cols = df.schema["tags"].dataType.names

df_map = df.withColumn(
    "tags_map",
    map_from_arrays(
        array(*[lit(c) for c in tags_cols]),
        array(*[col(f"tags.`{c}`") for c in tags_cols])
    )
)

df_long = df_map.select(
    "appid",
    explode("tags_map").alias("tag", "value")
)
df_long = df_long.filter(col("value").isNotNull() & (col("value") > 0))

top_tags = (
    df_long
    .groupBy("tag")
    .agg(count("*").alias("occurrences"))
    .orderBy(col("occurrences").desc())
)

In [0]:
top_tags.show(top_tags.count(),truncate=False)

+---------------------------------+-----------+
|tag                              |occurrences|
+---------------------------------+-----------+
|Indie                            |36062      |
|Singleplayer                     |27344      |
|Action                           |25022      |
|Casual                           |23993      |
|Adventure                        |23150      |
|2D                               |14547      |
|Strategy                         |11849      |
|Simulation                       |11599      |
|RPG                              |10161      |
|Puzzle                           |9719       |
|Atmospheric                      |9232       |
|Early Access                     |7629       |
|Pixel Graphics                   |7521       |
|3D                               |7430       |
|Story Rich                       |7359       |
|Multiplayer                      |6994       |
|Colorful                         |6974       |
|Arcade                           |6516       |
|Cute                             |6431       |
|First-Person                     |6155       |
|Fantasy                          |6116       |
|Exploration                      |6066       |
|Funny                            |5703       |
|Shooter                          |5563       |
|Retro                            |5482       |
|Platformer                       |5455       |
|Anime                            |5190       |
|Family Friendly                  |5147       |
|Horror                           |5127       |
|Sci-fi                           |5006       |
|VR                               |4878       |
|Difficult                        |4772       |
|Relaxing                         |4614       |
|Female Protagonist               |4376       |
|Action-Adventure                 |4246       |
|Great Soundtrack                 |4224       |
|Survival                         |3952       |
|Free to Play                     |3939       |
|Open World                       |3889       |
|Third Person                     |3781       |
|Violent                          |3625       |
|Top-Down                         |3517       |
|Comedy                           |3499       |
|Co-op                            |3452       |
|FPS                              |3413       |
|Visual Novel                     |3360       |
|Stylized                         |3231       |
|Controller                       |3219       |
|Minimalist                       |3154       |
|2D Platformer                    |3153       |
|Point & Click                    |3137       |
|Gore                             |3098       |
|Physics                          |3095       |
|Combat                           |2953       |
|Mystery                          |2951       |
|Sports                           |2887       |
|Cartoony                         |2885       |
|Psychological Horror             |2831       |
|Dark                             |2805       |
|PvP                              |2782       |
|Choices Matter                   |2773       |
|Realistic                        |2769       |
|Sandbox                          |2765       |
|Side Scroller                    |2722       |
|Space                            |2693       |
|Linear                           |2557       |
|Multiple Endings                 |2441       |
|Sexual Content                   |2404       |
|Nudity                           |2381       |
|Puzzle-Platformer                |2380       |
|Racing                           |2314       |
|Old School                       |2311       |
|Tactical                         |2299       |
|Local Multiplayer                |2272       |
|Management                       |2254       |
|Building                         |2252       |
|Hidden Object                    |2172       |
|Character Customization          |2143       |
|Rogue-like                       |2108       |
|Shoot 'Em Up                     |2094       |
|Logic                            |2091       |
|Action RPG                       |2056       |
|Hand-drawn                       |2031       |
|Magic                            |2003       |
|Procedural Generation            |1972       |
|Turn-Based Strategy              |1967       |
|Rogue-lite                       |1960       |
|PvE                              |1922       |
|3D Platformer                    |1858       |
|Survival Horror                  |1847       |
|Online Co-Op                     |1802       |
|Cartoon                          |1789       |
|Futuristic                       |1770       |
|Turn-Based Combat                |1752       |
|Local Co-Op                      |1742       |
|Replay Value                     |1723       |
|Bullet Hell                      |1714       |
|Zombies                          |1710       |
|Medieval                         |1708       |
|Crafting                         |1685       |
|Turn-Based                       |1678       |
|Turn-Based Tactics               |1645       |
|Hack and Slash                   |1637       |
|Education                        |1628       |
|JRPG                             |1603       |
|Massively Multiplayer            |1531       |
|Score Attack                     |1530       |
|Choose Your Own Adventure        |1530       |
|Walking Simulator                |1529       |
|Classic                          |1516       |
|Interactive Fiction              |1511       |
|Fast-Paced                       |1509       |
|War                              |1505       |
|Dungeon Crawler                  |1502       |
|Resource Management              |1495       |
|Historical                       |1487       |
|Short                            |1476       |
|1990's                           |1442       |
|Drama                            |1432       |
|Surreal                          |1396       |
|Dark Fantasy                     |1396       |
|Top-Down Shooter                 |1393       |
|Post-apocalyptic                 |1371       |
|Isometric                        |1325       |
|Stealth                          |1310       |
|RPGMaker                         |1307       |
|Romance                          |1299       |
|Action Roguelike                 |1296       |
|Memes                            |1264       |
|RTS                              |1255       |
|Base-Building                    |1249       |
|Text-Based                       |1230       |
|Nature                           |1202       |
|Abstract                         |1200       |
|Emotional                        |1193       |
|Card Game                        |1191       |
|Board Game                       |1173       |
|Immersive Sim                    |1169       |
|Third-Person Shooter             |1154       |
|Tower Defense                    |1132       |
|Military                         |1131       |
|Precision Platformer             |1120       |
|2.5D                             |1119       |
|Clicker                          |1115       |
|1980s                            |1101       |
|VR Only                          |1088       |
|Mature                           |1067       |
|Experimental                     |1061       |
|Dating Sim                       |1058       |
|Robots                           |1055       |
|Cyberpunk                        |1053       |
|4 Player Local                   |1050       |
|Detective                        |1042       |
|Aliens                           |1030       |
|Tabletop                         |1030       |
|Flight                           |1022       |
|Investigation                    |1021       |
|Narration                        |1020       |
|Driving                          |1019       |
|Perma Death                      |990        |
|Economy                          |978        |
|Time Management                  |965        |
|Dark Humor                       |960        |
|Fighting                         |956        |
|Arena Shooter                    |922        |
|Music                            |894        |
|Competitive                      |893        |
|Beat 'em up                      |886        |
|Real Time Tactics                |865        |
|Cinematic                        |864        |
|City Builder                     |863        |
|Runner                           |846        |
|Strategy RPG                     |842        |
|Psychological                    |829        |
|LGBTQ+                           |825        |
|Life Sim                         |817        |
|Psychedelic                      |805        |
|Utilities                        |797        |
|Demons                           |796        |
|Metroidvania                     |788        |
|Wargame                          |779        |
|Team-Based                       |771        |
|Thriller                         |753        |
|Tactical RPG                     |751        |
|Conversation                     |745        |
|Level Editor                     |744        |
|Tutorial                         |731        |
|Twin Stick Shooter               |728        |
|Automobile Sim                   |710        |
|Nonlinear                        |706        |
|2D Fighter                       |691        |
|Artificial Intelligence          |685        |
|Destruction                      |684        |
|Match 3                          |679        |
|Party-Based RPG                  |666        |
|Beautiful                        |661        |
|Loot                             |659        |
|Hentai                           |649        |
|Moddable                         |645        |
|Parkour                          |640        |
|Supernatural                     |632        |
|Dystopian                        |631        |
|Rhythm                           |627        |
|Grid-Based Movement              |625        |
|Modern                           |623        |
|Design & Illustration            |618        |
|Collectathon                     |617        |
|Comic Book                       |615        |
|Souls-like                       |607        |
|Idler                            |607        |
|Lore-Rich                        |590        |
|Space Sim                        |559        |
|Cats                             |556        |
|Alternate History                |553        |
|Crime                            |547        |
|CRPG                             |543        |
|World War II                     |543        |
|Soundtrack                       |532        |
|Character Action Game            |522        |
|Grand Strategy                   |518        |
|Mythology                        |498        |
|Mouse only                       |489        |
|Inventory Management             |483        |
|Split Screen                     |475        |
|Science                          |471        |
|Deckbuilding                     |461        |
|Dark Comedy                      |459        |
|Philosophical                    |456        |
|Card Battler                     |449        |
|e-sports                         |436        |
|Software                         |430        |
|3D Fighter                       |429        |
|Lovecraftian                     |428        |
|Swordplay                        |426        |
|Noir                             |424        |
|NSFW                             |422        |
|Mystery Dungeon                  |420        |
|6DOF                             |417        |
|Voxel                            |413        |
|Dragons                          |405        |
|Addictive                        |403        |
|Open World Survival Craft        |401        |
|Solitaire                        |398        |
|Battle Royale                    |397        |
|Word Game                        |396        |
|3D Vision                        |391        |
|Colony Sim                       |385        |
|Vehicular Combat                 |384        |
|MMORPG                           |384        |
|Blood                            |380        |
|Animation & Modeling             |380        |
|Mechs                            |377        |
|Bullet Time                      |371        |
|Farming Sim                      |360        |
|Combat Racing                    |359        |
|Steampunk                        |356        |
|Parody                           |355        |
|Real-Time                        |351        |
|Time Manipulation                |345        |
|Hero Shooter                     |345        |
|Game Development                 |341        |
|Automation                       |340        |
|Sokoban                          |338        |
|Spectacle fighter                |337        |
|Political                        |335        |
|Agriculture                      |332        |
|God Game                         |329        |
|America                          |327        |
|Hex Grid                         |326        |
|Capitalism                       |325        |
|Ninja                            |322        |
|Creature Collector               |318        |
|Remake                           |317        |
|Co-op Campaign                   |314        |
|FMV                              |311        |
|Martial Arts                     |309        |
|Tanks                            |306        |
|Pirates                          |303        |
|Gun Customization                |300        |
|Class-Based                      |299        |
|Cult Classic                     |297        |
|Conspiracy                       |294        |
|Satire                           |288        |
|Gothic                           |286        |
|Programming                      |283        |
|Video Production                 |282        |
|4X                               |280        |
|Time Travel                      |279        |
|Hunting                          |279        |
|Hacking                          |277        |
|Underground                      |277        |
|Underwater                       |275        |
|Trading                          |273        |
|Real-Time with Pause             |273        |
|Quick-Time Events                |272        |
|Mining                           |271        |
|Otome                            |271        |
|Dog                              |270        |
|Minigames                        |243        |
|Naval                            |241        |
|Dinosaurs                        |240        |
|Politics                         |239        |
|Touch-Friendly                   |239        |
|Auto Battler                     |237        |
|Trading Card Game                |236        |
|Audio Production                 |235        |
|Western                          |232        |
|Faith                            |231        |
|Superhero                        |231        |
|Illuminati                       |230        |
|Looter Shooter                   |230        |
|Time Attack                      |225        |
|Fishing                          |224        |
|Political Sim                    |224        |
|Cooking                          |224        |
|Party Game                       |221        |
|MOBA                             |219        |
|Escape Room                      |219        |
|Dynamic Narration                |209        |
|Vampire                          |207        |
|Typing                           |205        |
|Assassin                         |203        |
|Software Training                |201        |
|Cold War                         |200        |
|Asynchronous Multiplayer         |197        |
|Transportation                   |196        |
|Party                            |195        |
|Football                         |194        |
|Soccer                           |192        |
|Trivia                           |189        |
|Trains                           |187        |
|On-Rails Shooter                 |184        |
|Kickstarter                      |178        |
|Experience                       |176        |
|Narrative                        |174        |
|Music-Based Procedural Generation|171        |
|Immersive                        |167        |
|Villain Protagonist              |166        |
|Archery                          |162        |
|Diplomacy                        |161        |
|Naval Combat                     |160        |
|GameMaker                        |160        |
|Snow                             |156        |
|Offroad                          |152        |
|Chess                            |152        |
|Action RTS                       |151        |
|Sequel                           |147        |
|Sailing                          |147        |
|Episodic                         |145        |
|Heist                            |145        |
|Nostalgia                        |143        |
|Foreign                          |140        |
|Mars                             |140        |
|Traditional Roguelike            |134        |
|Gambling                         |134        |
|Horses                           |133        |
|Photo Editing                    |131        |
|Roguelike Deckbuilder            |130        |
|Boxing                           |127        |
|Sniper                           |126        |
|Web Publishing                   |116        |
|World War I                      |115        |
|Motorbike                        |112        |
|Golf                             |112        |
|Unforgiving                      |110        |
|Epic                             |109        |
|Jet                              |108        |
|Silent Protagonist               |108        |
|Cozy                             |106        |
|Werewolves                       |105        |
|Wholesome                        |104        |
|Spelling                         |103        |
|Rome                             |96         |
|Crowdfunded                      |95         |
|Bikes                            |94         |
|Pinball                          |93         |
|Farming                          |92         |
|Movie                            |90         |
|Outbreak Sim                     |89         |
|Transhumanism                    |88         |
|Asymmetric VR                    |87         |
|Spaceships                       |87         |
|Medical Sim                      |85         |
|LEGO                             |85         |
|Games Workshop                   |83         |
|Basketball                       |80         |
|Roguevania                       |79         |
|Submarine                        |77         |
|360 Video                        |77         |
|Based On A Novel                 |74         |
|Mini Golf                        |72         |
|Ambient                          |71         |
|Mod                              |68         |
|Vikings                          |66         |
|Social Deduction                 |62         |
|Electronic Music                 |61         |
|Lemmings                         |58         |
|Warhammer 40K                    |57         |
|Tennis                           |55         |
|Baseball                         |55         |
|Dungeons & Dragons               |54         |
|Intentionally Awkward Controls   |53         |
|Gaming                           |52         |
|Wrestling                        |51         |
|Pool                             |51         |
|Motocross                        |50         |
|Skateboarding                    |43         |
|Hockey                           |39         |
|Cycling                          |38         |
|Bowling                          |37         |
|Skating                          |36         |
|TrackIR                          |31         |
|Rock Music                       |29         |

On remarque que "tags" contient à la fois des éléments qui décrivent le type de jeu (rpg,MMORPG,Simulation,Shooter,Platformer etc.) mais également, l'univers dans lequel se situe le jeu (Sci-fi,Medieval, etc.) ou encore l'esthétique ou le gameplay. La colonne n'est pas exploitable telle quelle, il y a trop de nettoyage à faire dessus.

==> Nous préférons la supprimer du dataframe principal et lui consacrer un dataframe spécifique pour améliorer les performances de traitement et alléger le schéma.

In [0]:
tag_cols = df.select("tags.*").columns

df_tags = (
    df.select(
        "appid",
        F.explode(
            F.array([
                F.struct(
                    F.lit(c).alias("tag"),
                    F.col(f"tags.`{c}`").alias("occurrences")
                )
                for c in tag_cols
            ])
        ).alias("tag_struct")
    )
    .select(
        "appid",
        F.col("tag_struct.tag"),
        F.col("tag_struct.occurrences")
    )
    .filter(F.col("occurrences") > 0)
)

In [0]:
print("Structure du dataframe df_tags :")
df_tags.printSchema()

Structure du dataframe df_tags :
root
 |-- appid: long (nullable = true)
 |-- tag: string (nullable = false)
 |-- occurrences: long (nullable = true)

Nous allons créer trois autres dataframes pour améliorer les performances et rendre la structure de l'information plus cohérente :

- df_platforms : listant les différentes plateformes sur lesquelles les jeux sont déployées
- df_categories : listant les différentes catégories de classification des jeux
- df_publisher : liste des éditeurs des jeux.

### 2.2 table des plateformes

In [0]:
df_platforms = (
    df.select(
        "appid",
        F.col("platforms.windows").alias("Windows"),
        F.col("platforms.mac").alias("Mac"),
        F.col("platforms.linux").alias("Linux"),
    )
)

print("Structure du dataframe df_platforms :")
df_platforms.printSchema()

Structure du dataframe df_platforms :
root
 |-- appid: long (nullable = true)
 |-- Windows: boolean (nullable = true)
 |-- Mac: boolean (nullable = true)
 |-- Linux: boolean (nullable = true)

### 2.3 table des catégories

In [0]:
df_categories = (
    df
    .select("appid", F.explode("categories").alias("category"))
    
    .withColumn(
        "category_group",
        
        # Gameplay mode
        F.when(F.col("category").isin(
            "Single-player",
            "Multi-player",
            "Online Multi-Player",
            "LAN Multi-Player",
            "Shared/Split Screen",
            "Shared/Split-Screen",
            "Co-op",
            "Online Co-op",
            "LAN Co-op",
            "MMO",
            "PvP",
            "Online PvP",
            "LAN PvP",
            "Shared/Split Screen PvP",
            "Cross-Platform Multiplayer",
            "Shared/Split Screen Co-op",
            "Steam Turn Notifications"
        ), "Gameplay mode")
        
        # Community / Social
        .when(F.col("category").isin(
            "Steam Achievements",
            "Steam Leaderboards",
            "Steam Workshop",
            "Stats",
            "Includes level editor",
            "Mods",
            "Mods (require HL2)",
            "Includes Source SDK",
            "Valve Anti-Cheat Activated",
            "Valve Anti-Cheat enabled"
        ), "Community / Social")
        
        # Device / Hardware support
        .when(F.col("category").isin(
            "Full controller support",
            "Partial Controller Support",
            "Tracked Controller Support",
            "VR Supported",
            "VR Support",
            "VR Only",
            "Steam Cloud",
            "Remote Play on Phone",
            "Remote Play on Tablet",
            "Remote Play on TV",
            "Remote Play Together"
        ), "Device / Hardware support")
        
        # Accessibility / UX
        .when(F.col("category").isin(
            "Captions available",
            "Commentary available"
        ), "Accessibility / UX")
        
        # Monetization / Content
        .when(F.col("category").isin(
            "In-App Purchases",
            "Downloadable Content",
            "Steam Trading Cards",
            "SteamVR Collectibles"
        ), "Monetization / Content")
        
        # fallback
        .otherwise("Other")
    )
)

print("Structure du dataframe df_categories :")
df_categories.printSchema()

Structure du dataframe df_categories :
root
 |-- appid: long (nullable = true)
 |-- category: string (nullable = true)
 |-- category_group: string (nullable = false)

### 2.4 table des éditeurs

In [0]:
suffixes = [
    ", Inc.",
    ", Ltd.",
    ", LTD.",
    ", LLC",
    ", Co., Ltd.",
    ", Co.,Ltd.",
    ", GmbH",
    ", S.A.",
    ", S.r.l."
]

df_publisher = df.withColumn("publisher_clean", F.col("publisher"))

for s in suffixes:
    df_publisher = df_publisher.withColumn(
        "publisher_clean",
        F.regexp_replace("publisher_clean", s, s.replace(",", "§"))
    )

df_publisher = (
    df_publisher
    .withColumn("publisher", F.explode(F.split(F.col("publisher_clean"), ",")))
    .withColumn("publisher", F.trim(F.col("publisher")))
    .withColumn("publisher", F.regexp_replace("publisher", "§", ","))
    .filter(F.col("publisher") != "")
    .select("appid", "publisher")
)

print("Structure du dataframe df_publisher :")
df_publisher.printSchema()

Structure du dataframe df_publisher :
root
 |-- appid: long (nullable = true)
 |-- publisher: string (nullable = false)

### 2.5 Table des genres

In [0]:
df_genres = (
    df
    .select("appid", "genre")
    .filter(F.col("genre").isNotNull())
    .withColumn("genre_array", F.split(F.col("genre"), ","))
    .withColumn("genre", F.explode("genre_array"))
    .withColumn("genre", F.trim(F.col("genre")))
    .filter(F.col("genre") != "")
    .select("appid", "genre")
)
print("Structure du dataframe df_genres :")
df_genres.printSchema()

Structure du dataframe df_genres :
root
 |-- appid: long (nullable = true)
 |-- genre: string (nullable = false)

### 2.6 Suppression des colonnes inutiles dans la table principale

Sélection des colonnes à supprimer du dataframe principal.

In [0]:
col_to_drop =[
    "id",
    "developer",
    "tags",
    "categories",
    "platforms",
    "ccu",
    "publisher",
    "header_image",
    "short_description",
    "website"
]

In [0]:
df = df.drop(*col_to_drop)
print("Structure du dataframe principal df :")
df.printSchema()

Structure du dataframe principal df :
root
 |-- appid: long (nullable = true)
 |-- discount: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- initialprice: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- negative: long (nullable = true)
 |-- owners: string (nullable = true)
 |-- positive: long (nullable = true)
 |-- price: string (nullable = true)
 |-- release_date: string (nullable = true)
 |-- required_age: string (nullable = true)
 |-- type: string (nullable = true)
 |-- initialprice_eur: double (nullable = true)
 |-- price_eur: double (nullable = true)
 |-- required_age_num: integer (nullable = true)
 |-- is_adult_game: boolean (nullable = true)
 |-- owners_clean: string (nullable = true)
 |-- owners_min: long (nullable = true)
 |-- owners_max: long (nullable = true)
 |-- owners_avg: double (nullable = true)
 |-- release_date_dt: date (nullable = true)
 |-- release_year: integer (nullable = true)
 |-- release_month: integer (nullable = true)
 |-- reviews_total: long (nullable = false)
 |-- pos_ratio: double (nullable = true)
 |-- steam_score: double (nullable = true)

test de la présence de doublons dans df

In [0]:
df.groupBy("appid").count().orderBy(F.desc("count")).show(10)

+-------+-----+
|  appid|count|
+-------+-----+
|1005130|    1|
|1002420|    1|
|1003090|    1|
|1003940|    1|
|1000990|    1|
|1002360|    1|
|1000470|    1|
|1001960|    1|
|1001040|    1|
|1003750|    1|
+-------+-----+
only showing top 10 rows

In [0]:
df.printSchema()

root
 |-- appid: long (nullable = true)
 |-- discount: string (nullable = true)
 |-- genre: string (nullable = true)
 |-- initialprice: string (nullable = true)
 |-- languages: string (nullable = true)
 |-- name: string (nullable = true)
 |-- negative: long (nullable = true)
 |-- owners: string (nullable = true)
 |-- positive: long (nullable = true)
 |-- price: string (nullable = true)
 |-- release_date: string (nullable = true)
 |-- required_age: string (nullable = true)
 |-- type: string (nullable = true)
 |-- initialprice_eur: double (nullable = true)
 |-- price_eur: double (nullable = true)
 |-- required_age_num: integer (nullable = true)
 |-- is_adult_game: boolean (nullable = true)
 |-- owners_clean: string (nullable = true)
 |-- owners_min: long (nullable = true)
 |-- owners_max: long (nullable = true)
 |-- owners_avg: double (nullable = true)
 |-- release_date_dt: date (nullable = true)
 |-- release_year: integer (nullable = true)
 |-- release_month: integer (nullable = true)
 |-- reviews_total: long (nullable = false)
 |-- pos_ratio: double (nullable = true)
 |-- steam_score: double (nullable = true)

Contrôle des outliers

recherche des outliers prix

In [0]:
df.orderBy(F.desc("price_eur")).select("name","price_eur").show(20, False)

+-----------------------------------------------------------------+---------+
|name                                                             |price_eur|
+-----------------------------------------------------------------+---------+
|Ascent Free-Roaming VR Experience                                |999.0    |
|Aartform Curvy 3D 3.0                                            |299.9    |
|Houdini Indie                                                    |269.99   |
|VEGAS Edit 20 Steam Edition                                      |249.0    |
|Arcade Drift                                                     |199.99   |
|VR Long March                                                    |199.99   |
|fight                                                            |199.99   |
|眼睛（眼球）结构研究                                             |199.99   |
|Earthquake escape                                                |199.99   |
|VRemedies - MRI Procedure Experience                             |199.99   |
|The Island of Dr. Yepstein                                       |199.99   |
|Spot Sample Witness Simulator                                    |199.99   |
|Virtual Orator                                                   |199.99   |
|Reincarnation of Ocean                                           |199.99   |
|RagingFist                                                       |199.99   |
|Run Thief                                                        |199.99   |
|Chandrayaan VR                                                   |199.99   |
|Lgnorant girl doll                                               |199.99   |
|3DF Zephyr Lite Steam Edition                                    |199.99   |
|Home Architect - Design your floor plans in 3D - Ultimate Edition|199.99   |
+-----------------------------------------------------------------+---------+
only showing top 20 rows

Les prix semblent très important, trop pour des jeux. Il s'agit en fait d'outils de développement, d'expériences VR ou, pour "Ascent free roaming VR experience", d'un jeu intégrant la VR, des sols vibrants, les sensations aptiques etc. Ce jeu est principalement destiné aux professionnels ayant un équipement spécifique.

recherche de ratios négatifs ou >1

In [0]:
df.select(F.min("pos_ratio"),F.max("pos_ratio")).show()

+--------------+--------------+
|min(pos_ratio)|max(pos_ratio)|
+--------------+--------------+
|           0.0|           1.0|
+--------------+--------------+

Il ne semble pas y avoir d'éléments problématiques.

# 3. Croissance du catalogue Steam

### 3.1 Nombre de jeux publiés chaque année

In [0]:
df_games_per_year = (
    df.filter(F.col("release_year").isNotNull())
      .groupBy("release_year")
      .agg(F.count("*").alias("n_games"))
      .orderBy("release_year")
)
display(df_games_per_year)

release_year,n_games
1997,2
1998,1
1999,3
2000,2
2001,4
2002,1
2003,3
2004,6
2005,6
2006,61
2007,98
2008,159
2009,311
2010,288
2011,267
2012,345
2013,471
2014,1557
2015,2575
2016,4185
2017,6017
2018,7678
2019,6968
2020,8305
2021,8823
2022,7455

Databricks visualization. Run in Databricks to view.

Les volumes de sorties annuelles augmentent fortement entre 2012 et 2018, ce qui correspond à une phase d’expansion rapide du catalogue Steam.

À partir de 2019, la croissance ralentit et le nombre de nouvelles publications semble se stabiliser, voire légèrement diminuer certaines années.

Ce ralentissement apparaît avant la pandémie de COVID-19. Il est donc difficile de l’attribuer directement à cet événement. L’année 2020, la plus fortement marquée par la pandémie, ne montre pas de chute brutale du nombre de sorties et s’inscrit plutôt dans une phase de reprise du volume de publications.

On peut formuler l’hypothèse que les périodes de confinement ont pu favoriser le développement de projets indépendants, mais cette interprétation ne peut pas être confirmée à partir des données disponibles dans ce dataset.

#### 3.2 Nombre d'éditeurs ayant sorti au moins un jeu chaque année

In [0]:
df_publishers_per_year = (
    df.filter(F.col("release_year").isNotNull())
      .select("appid", "release_year")
      .join(df_publisher.select("appid", "publisher"), on="appid", how="inner")
      .filter(F.col("publisher").isNotNull() & (F.trim(F.col("publisher")) != ""))
      .groupBy("release_year")
      .agg(F.countDistinct("publisher").alias("n_publishers"))
      .orderBy(F.col("release_year").asc())
)

display(df_publishers_per_year)

release_year,n_publishers
1997,2
1998,1
1999,2
2000,1
2001,3
2002,1
2003,3
2004,2
2005,6
2006,30
2007,37
2008,72
2009,122
2010,133
2011,160
2012,228
2013,304
2014,887
2015,1774
2016,3005
2017,4406
2018,5553
2019,5348
2020,6361
2021,6504
2022,5802

Databricks visualization. Run in Databricks to view.

l'évolution du nombre d'éditeurs suit exactement la même tendance que pour le nombre de jeux sortis par année, seuls les volumes varient : ils sont logiquement moins importants pour le nombre d'éditeurs.

# 4. Structure des éditeurs

### 4.1 Top éditeurs par nombre de jeux

In [0]:

df_games_per_publisher = (
    df_publisher
    .groupBy("publisher")
    .agg(F.countDistinct("appid").alias("n_games"))
    .orderBy(F.desc("n_games"))
    .limit(20)
)

display(df_games_per_publisher)

publisher,n_games
Big Fish Games,423
8floor,202
SEGA,187
Square Enix,151
Strategy First,151
THQ Nordic,144
Choice of Games,140
Sekai Project,136
Plug In Digital,136
HH-Games,132
Electronic Arts,128
Ubisoft,128
Laush Studio,126
Alawar Entertainment,113
Ziggurat,112
Fulqrum Publishing,107
Devolver Digital,106
Slitherine Ltd.,102
PLAYISM,101
Sokpop Collective,100

Databricks visualization. Run in Databricks to view.

On remarque que ce sont majoritairement des éditeurs indépendants qui sortent le plus de jeux. Ceci semble logique dans le sens où les jeux indépendant sont souvent moins lourds à développer que des AAA de grosses franchises. cette répartition est cohérente avec la structure du catalogue de jeux Steam.

Quelques très gros éditeurs apparaissent cependant dans le top 20 : Sega, Square Enix, THQ Nordic, Electronic Arts (EA), Ubisoft

### 4.2 Top 15 du nombre de jeux sortis par éditeur par année

In [0]:
TOP_N = 15

# Base: année par appid
df_year = (
    df.select("appid", "release_year")
      .filter((F.col("release_year") >= 2012) & (F.col("release_year") <= 2022))
      .filter(F.col("release_year").isNotNull())
)

# Publishers: 1 ligne par (appid, publisher) déjà nettoyé chez toi
df_pub = (
    df_publisher
      .select("appid", F.col("publisher").alias("publisher_clean"))
      .filter(F.col("publisher_clean").isNotNull() & (F.trim(F.col("publisher_clean")) != ""))
)

# Join + agrégat
df_pub_year = (
    df_year.join(df_pub, on="appid", how="inner")
           .groupBy("release_year", "publisher_clean")
           .agg(F.count("*").alias("n_games"))
)

# Top N par année
w = Window.partitionBy("release_year").orderBy(F.desc("n_games"), F.asc("publisher_clean"))

df_pub_top = (
    df_pub_year
      .withColumn("rank", F.row_number().over(w))
      .filter(F.col("rank") <= TOP_N)
      .drop("rank")
)

# Collect pour Plotly
pdf = df_pub_top.orderBy(F.desc("release_year"), F.desc("n_games")).toPandas()
years = sorted(pdf["release_year"].unique(), reverse=True)

# Subplots
ncols = 3
nrows = math.ceil(len(years) / ncols)

fig = make_subplots(
    rows=nrows,
    cols=ncols,
    subplot_titles=[str(y) for y in years],
    horizontal_spacing=0.08,
    vertical_spacing=0.12
)

for i, year in enumerate(years):
    r = i // ncols + 1
    c = i % ncols + 1

    d = (
        pdf[pdf["release_year"] == year]
        .sort_values(["n_games", "publisher_clean"], ascending=[False, True])
        .head(TOP_N)
    )

    fig.add_trace(
        go.Bar(
            x=d["n_games"],
            y=d["publisher_clean"],
            orientation="h",
            showlegend=False
        ),
        row=r,
        col=c
    )

    fig.update_yaxes(autorange="reversed", row=r, col=c)

fig.update_layout(
    height=320 * nrows,
    title=f"Top {TOP_N} publishers par année (2012–2022)",
    margin=dict(l=40, r=20, t=60, b=30)
)

fig.show()

On remarque que, pour les années 2012 et 2013, des très gros éditeurs étaient présents dans le top des volumes de sorties (2012 : SEGA, THQ Nordic ; 2013 : Square Enix, Ubisoft, BANDAI NAMCO, Paradox Interactive).

cependant, les années suivantes, ils disparaissent globalement du top 15. Cela peut s'expliquer par l'accroissement du volume de jeux sortis par les développeurs les plus prolifiques. En 2012 et 2013, l'éditeur ayant sorti le plus grand nombre de jeux en a sorti, respectivement 21 et 11.... en 2021 et 2022, ce sont 66 et 46 jeux qui ont été sortis en une année par un éditeur...

le pic s'étant produit en 2017 avec 112 jeux pour Big Fish Games !!!

Certains éditeurs sont spécialisés dans des genres de petits jeux courts et peu coûteux à développer  et peuvent, ainsi, en sortir une grande quantité en une année.

# 5. Plateformes

### 5.1 Ventilation des jeux par plateforme supportée

In [0]:
total_games = df_platforms.select(F.countDistinct("appid")).collect()[0][0]

df_platform_share = (
    df_platforms
    .agg(
        F.sum(F.col("Windows").cast("int")).alias("windows_games"),
        F.sum(F.col("Mac").cast("int")).alias("mac_games"),
        F.sum(F.col("Linux").cast("int")).alias("linux_games")
    )
    .withColumn("windows_pct", F.round(F.col("windows_games")/total_games*100,2))
    .withColumn("mac_pct", F.round(F.col("mac_games")/total_games*100,2))
    .withColumn("linux_pct", F.round(F.col("linux_games")/total_games*100,2))
)

display(df_platform_share)

windows_games,mac_games,linux_games,windows_pct,mac_pct,linux_pct
55675,12769,8457,99.97,22.93,15.19

Databricks visualization. Run in Databricks to view.

La totalité des jeux présents dans le catalogue Steam au moment de l'extraction est jouable sur PC. Ce n'est pas le cas du tout pour les Mac (22,93% des jeux sont jouables sur Mac) et encore moins pour Linux (15,19% des jeux sont jouables sur Linux).

### 5.2 part des jeux "Windows only" dans l'extraction

In [0]:
df_platform_types = (
    df_platforms
    .withColumn(
        "platform_type",
        F.when(
            (F.col("Windows") == True) &
            (F.col("Mac") == False) &
            (F.col("Linux") == False),
            "Windows only"
        )
        .when(
            (F.col("Windows") == True) &
            ((F.col("Mac") == True) | (F.col("Linux") == True)),
            "Windows + Mac/Linux"
        )
        .otherwise("Mac/Linux without Windows")
    )
)

total_games = df_platform_types.select(F.countDistinct("appid")).collect()[0][0]

df_platform_distribution = (
    df_platform_types
    .groupBy("platform_type")
    .agg(F.countDistinct("appid").alias("n_games"))
    .withColumn(
        "share_pct",
        F.round(F.col("n_games") / F.lit(total_games) * 100, 2)
    )
)

display(df_platform_distribution)

platform_type,n_games,share_pct
Mac/Linux without Windows,15,0.03
Windows + Mac/Linux,14404,25.86
Windows only,41271,74.11

Databricks visualization. Run in Databricks to view.


Une grande majorité des jeux sont édités "Windows only", ce qui signifie qu'ils ne seront jamais adaptés pour d'autres plateformes. Cela représente, au moment de l'extraction du dataset, 74,11% du catalogue disponible.

Mac et Linux sont relégués à un rôle de support secondaire. Cette part très importante de jeux Windows only biaise la distribution globale.

#### 5.2.1 Evolution de la part des jeux "Windows only" dans le temps

In [0]:
df_platform_year = (
    df_platforms
    .join(df.select("appid","release_year"), "appid")
    .filter(F.col("release_year").isNotNull())
    .filter(F.col("release_year") > 2006)
)

df_platform_year = df_platform_year.withColumn(
    "windows_only",
    (
        (F.col("Windows") == True) &
        (F.col("Mac") == False) &
        (F.col("Linux") == False)
    ).cast("int")
)

df_windows_only_share = (
    df_platform_year
    .groupBy("release_year")
    .agg(
        F.countDistinct("appid").alias("n_games"),
        F.sum("windows_only").alias("windows_only_games")
    )
    .withColumn(
        "windows_only_pct",
        F.round(F.col("windows_only_games") / F.col("n_games") * 100, 2)
    )
    .orderBy("release_year")
)

display(
    df_windows_only_share.select(
        "release_year",
        "windows_only_pct"
    )
)

release_year,windows_only_pct
2007,88.78
2008,88.05
2009,78.14
2010,65.63
2011,67.04
2012,57.39
2013,50.32
2014,55.49
2015,54.49
2016,62.72
2017,70.43
2018,73.33
2019,76.16
2020,78.01
2021,81.28
2022,82.55

Databricks visualization. Run in Databricks to view.


On remarque qu'entre 2008 et 2013, la part de jeux sortis chaque année et réservés à Windows a fortement diminué, passant de 88,78% en 2007 à 50,32% en 2013.

A partir de 2014, avec l'explosion des publications de jeux sur Steam, la part des jeux "Windows only" a de nouveau cru et atteint, pour les jeux sortis en 2022 82,55% soit légèrement moins qu'en 2007.

### 5.3 Evolution de la part des jeux disponible pour chaque plateforme selon l'année de sortie

In [0]:

df_platform_year = (
    df_platforms
    .join(df.select("appid", "release_year"), "appid")
    .filter(F.col("release_year").isNotNull())
    .filter(F.col("release_year")>=2006)
)

df_platform_year_share = (
    df_platform_year
    .groupBy("release_year")
    .agg(
        F.countDistinct("appid").alias("n_games"),
        F.sum(F.col("Windows").cast("int")).alias("windows_games"),
        F.sum(F.col("Mac").cast("int")).alias("mac_games"),
        F.sum(F.col("Linux").cast("int")).alias("linux_games")
    )
    .withColumn("windows_pct", F.round(F.col("windows_games")/F.col("n_games")*100,2))
    .withColumn("mac_pct", F.round(F.col("mac_games")/F.col("n_games")*100,2))
    .withColumn("linux_pct", F.round(F.col("linux_games")/F.col("n_games")*100,2))
    .orderBy("release_year")
)

display(
    df_platform_year_share.select(
        "release_year",
        "windows_pct",
        "mac_pct",
        "linux_pct"
    )
)

release_year,windows_pct,mac_pct,linux_pct
2006,100.0,26.23,16.39
2007,100.0,11.22,4.08
2008,100.0,10.06,3.77
2009,100.0,21.22,8.68
2010,100.0,34.03,20.49
2011,100.0,30.71,17.98
2012,99.71,41.74,27.25
2013,100.0,46.71,38.22
2014,100.0,42.45,29.67
2015,99.96,41.94,30.64
2016,99.98,34.55,23.89
2017,99.93,27.24,18.3
2018,99.97,24.19,14.57
2019,99.97,20.85,12.3
2020,100.0,18.56,11.57
2021,99.98,15.32,10.46
2022,99.97,13.98,10.61

Databricks visualization. Run in Databricks to view.

Au début des années 2010, grâce à une visibilité croissante des joueurs Linux et Mac demandant un accès à une bibliothèque plus importante, un passage des nouveaux Mac sur des puces Intel (entre 2006 et 2007) facilitant la portabilité des jeux sur cette plateforme, l'arrivée d'Android (basé sur Linux) ainsi qu'une amélioration en termes de qualité et de fréquence de mise à jour des pilotes de cartes graphiques pour Linux par les deux géants AMD et Nvidia, la proportion de jeux accessibles aux ordinateurs Mac et Linux a crû pendant quelques années pour atteindre un pic à 46,71% des jeux sortis en 2013 disponibles sur Mac et 38,22% pour Linux. Cette tendance s'est inversée à partir de 2014 pour redescendre doucement, pour les sorties 2022, à un niveau égale à celui de 2007 pour les Mac et 2009 pour Linux.

#### 5.3.1 Evolution de la part des jeux disponibles sur chaque plateforme, en excluant les jeux "Windows Only"

In [0]:
df_platform_year = (
    df_platforms
    .join(df.select("appid", "release_year"), "appid")
    .filter(F.col("release_year").isNotNull())
    .filter(F.col("release_year") >= 2006)

    # exclusion des jeux Windows-only
    .filter(
        ~(
            (F.col("Windows") == True) &
            (F.col("Mac") == False) &
            (F.col("Linux") == False)
        )
    )
)

df_platform_year_share = (
    df_platform_year
    .groupBy("release_year")
    .agg(
        F.countDistinct("appid").alias("n_games"),
        F.sum(F.col("Windows").cast("int")).alias("windows_games"),
        F.sum(F.col("Mac").cast("int")).alias("mac_games"),
        F.sum(F.col("Linux").cast("int")).alias("linux_games")
    )
    .withColumn("windows_pct", F.round(F.col("windows_games")/F.col("n_games")*100,2))
    .withColumn("mac_pct", F.round(F.col("mac_games")/F.col("n_games")*100,2))
    .withColumn("linux_pct", F.round(F.col("linux_games")/F.col("n_games")*100,2))
    .orderBy("release_year")
)

display(
    df_platform_year_share.select(
        "release_year",
        "windows_pct",
        "mac_pct",
        "linux_pct"
    )
)

release_year,windows_pct,mac_pct,linux_pct
2006,100.0,100.0,62.5
2007,100.0,100.0,36.36
2008,100.0,84.21,31.58
2009,100.0,97.06,39.71
2010,100.0,98.99,59.6
2011,100.0,93.18,54.55
2012,99.32,97.96,63.95
2013,100.0,94.02,76.92
2014,100.0,95.38,66.67
2015,99.91,92.15,67.32
2016,99.94,92.69,64.1
2017,99.78,92.13,61.89
2018,99.9,90.67,54.64
2019,99.88,87.48,51.6
2020,100.0,84.39,52.63
2021,99.88,81.84,55.87
2022,99.85,80.09,60.8

Databricks visualization. Run in Databricks to view.

Il est nécessaire de garder en tête que ce graphique ne représente que 26% du catalogue global Steam au moment de l'extraction.

Cependant, on observe une nette progression des proportions de jeux publiés à la fois sur Windows et sur au moins l'une des autres plateformes.

Jusqu'en 2012, la quasi totalité des jeux (hors "Windows Only") était publiée également sur Mac. Cette proportioncommence à diminuer de manière régulière à partir de 2013 et continue jusqu'en 2022 pour atteindre 80,1%.

Concernant Linux, après une forte progression sur la période 2008 - 2013 où 76,9% des jeux (hors "Windows Only") ont également été publiés sur cette plateforme, on constate une diminution jusqu'en 2019. Cette baisse correspond à la période où la publication de jeux a explosé, sur Steam.

Entre 2019 et 2022, avec la baisse du nombre de jeux sortis chaque année, la part des jeux publiés également sur Linux a, de nouveau, recommencé à croitre.

In [0]:

df_platform_year = (
    df_platforms
    .join(df.select("appid", "release_year"), "appid")
    .filter(F.col("release_year").isNotNull())
    .filter(F.col("release_year") >= 2006)
)

df_platform_counts = (
    df_platform_year
    .groupBy("release_year")
    .agg(
        F.countDistinct("appid").alias("n_games_total"),
        F.countDistinct(
            F.when(F.col("Mac") == True, F.col("appid"))
        ).alias("mac_games"),
        F.countDistinct(
            F.when(F.col("Linux") == True, F.col("appid"))
        ).alias("linux_games")
    )
    .orderBy("release_year")
)

display(
    df_platform_counts.select(
        "release_year",
        "mac_games",
        "linux_games"
    )
)

release_year,mac_games,linux_games
2006,16,10
2007,11,4
2008,16,6
2009,66,27
2010,98,59
2011,82,48
2012,144,94
2013,220,180
2014,661,462
2015,1080,789
2016,1446,1000
2017,1639,1101
2018,1857,1119
2019,1453,857
2020,1541,961
2021,1352,923
2022,1042,791

Databricks visualization. Run in Databricks to view.

Cette baisse proportionnelle (période 2014-2019 pour Linux et 2013-2022 pour Mac) est, en partie, un trompe l'oeil car le volume de jeux édités pour Mac et Linux est en croissance constante jusqu'en 2018 mais le volume total de jeux édités chaque année a crû encore plus rapidement et écrase donc la propotion de jeux disponibles sur Mac et Linux.

A partir de 2019 on constate, comme pour Windows, une diminuton du volume de sorties.

### 5.4 Genres les plus représentés par plateforme

In [0]:
# Passage des plateformes en format long
df_platform_long = (
    df_platforms
    .select("appid", "Windows", "Mac", "Linux")
    .withColumn("platform_array",
        F.array(
            F.struct(F.lit("Windows").alias("platform"), F.col("Windows").alias("available")),
            F.struct(F.lit("Mac").alias("platform"), F.col("Mac").alias("available")),
            F.struct(F.lit("Linux").alias("platform"), F.col("Linux").alias("available"))
        )
    )
    .withColumn("platform_struct", F.explode("platform_array"))
    .select(
        "appid",
        F.col("platform_struct.platform").alias("platform"),
        F.col("platform_struct.available").alias("available")
    )
    .filter(F.col("available") == True)
)

# Jointure genres + plateformes
df_genre_platform = df_genres.join(df_platform_long, "appid")

# Comptage des genres par plateforme
df_genre_distribution = (
    df_genre_platform
    .groupBy("platform", "genre")
    .count()
)

# Calcul des proportions par plateforme
w_platform = Window.partitionBy("platform")

df_genre_distribution = (
    df_genre_distribution
    .withColumn("total_platform", F.sum("count").over(w_platform))
    .withColumn("proportion", (F.col("count") / F.col("total_platform")) * 100)
)

# Top 10 genres par plateforme
w_rank = Window.partitionBy("platform").orderBy(F.desc("proportion"))

top_genres = (
    df_genre_distribution
    .withColumn("rank", F.row_number().over(w_rank))
    .filter(F.col("rank") <= 10)
    .select("platform", "genre", "proportion", "count")
)

display(top_genres)

platform,genre,proportion,count
Linux,Indie,29.08833215223644,6978
Linux,Action,14.085622577014464,3379
Linux,Casual,13.777147859435573,3305
Linux,Adventure,13.764642127641835,3302
Linux,Strategy,7.611822085122348,1826
Linux,Simulation,6.386260369335946,1532
Linux,RPG,6.352911751219309,1524
Linux,Early Access,2.6345408312143066,632
Linux,Free to Play,1.97590562341073,474
Linux,Racing,1.2672474884321983,304
Mac,Indie,27.6725530611108,9935
Mac,Casual,14.288897554453792,5130
Mac,Adventure,14.035429781070693,5039
Mac,Action,12.71238371121386,4564
Mac,Strategy,8.370007241936381,3005
Mac,Simulation,6.793493398696452,2439
Mac,RPG,6.261489610606652,2248
Mac,Early Access,2.506824132360314,900
Mac,Free to Play,2.3536293242716284,845
Mac,Sports,1.40939223441591,506
Windows,Indie,25.259110239629223,39676
Windows,Action,15.123252438310116,23755
Windows,Casual,14.058162927500065,22082
Windows,Adventure,13.641167333010774,21427
Windows,Strategy,6.93422292393491,10892
Windows,Simulation,6.8960248542107,10832
Windows,RPG,6.069036644681555,9533
Windows,Early Access,3.912118974254501,6145
Windows,Free to Play,2.158827573913265,3391
Windows,Sports,1.6966309302503246,2665

Databricks visualization. Run in Databricks to view.

# 6. Langues

### 6.1 Langues les plus supportées

In [0]:
# Total de jeux uniques dans le dataset (aucune valeur hardcodée)
total_games_df = df.select("appid").distinct().agg(
    F.count("*").alias("total_games")
)

# Explose les langues, nettoie et déduplique au niveau jeu-langue
df_languages_clean = (
    df
    .select("appid", "languages")
    .filter(F.col("appid").isNotNull() & F.col("languages").isNotNull())
    .withColumn("language", F.explode(F.split(F.col("languages"), ",")))
    .withColumn("language", F.trim(F.col("language")))
    .filter(F.col("language") != "")
    .select("appid", "language")
    .dropDuplicates(["appid", "language"])
)

# Nombre de jeux par langue
df_lang_counts = (
    df_languages_clean
    .groupBy("language")
    .agg(F.countDistinct("appid").alias("games_supporting_language"))
)

# Pourcentage de jeux supportant chaque langue
df_lang_pct = (
    df_lang_counts
    .crossJoin(total_games_df)
    .withColumn(
        "pct_games",
        F.round(F.col("games_supporting_language") / F.col("total_games") * 100, 2)
    )
    .orderBy(F.desc("pct_games"), F.desc("games_supporting_language"))
    .limit(20)
)

display(df_lang_pct)

language,games_supporting_language,total_games,pct_games
English,55116,55690,98.97
German,14019,55690,25.17
French,13426,55690,24.11
Russian,12922,55690,23.2
Simplified Chinese,12782,55690,22.95
Spanish - Spain,12233,55690,21.97
Japanese,10368,55690,18.62
Italian,9304,55690,16.71
Portuguese - Brazil,6750,55690,12.12
Korean,6600,55690,11.85
Traditional Chinese,6307,55690,11.33
Polish,5376,55690,9.65
Portuguese - Portugal,4011,55690,7.2
Turkish,3602,55690,6.47
Dutch,3080,55690,5.53
Spanish - Latin America,2732,55690,4.91
Czech,2352,55690,4.22
Swedish,2047,55690,3.68
Ukrainian,1928,55690,3.46
Hungarian,1923,55690,3.45

Databricks visualization. Run in Databricks to view.

La totalité ou presque des jeux supporte l'anglais. Les langues les plus supportées, après l'anglais, sont très loin derrière.

Seul 25,17% des jeux supportent l'allemand et 24,11% le français. viennent ensuite le russe (23,2%), le chinois simplifié (22,95%), l'espagnol (21,97)

#### 6.1.1 Jeux ne supportant pas l'anglais

In [0]:
df_languages = (
    df
    .select("appid", "name", "languages")
    .filter(F.col("languages").isNotNull())
    .withColumn("language", F.explode(F.split("languages", ",")))
    .withColumn("language", F.trim("language"))
    .select("appid", "name", "language")
)

df_games_with_english = (
    df_languages
    .filter(F.lower(F.col("language")) == "english")
    .select("appid")
    .distinct()
)

df_games_no_english = (
    df
    .join(df_games_with_english, on="appid", how="left_anti")
)

df_no_eng_languages = (
    df_games_no_english
    .select("appid", "languages")
    .withColumn("language", F.explode(F.split("languages", ",")))
    .withColumn("language", F.trim("language"))
)

display(df_no_eng_languages.groupBy("language") \
    .count() \
    .orderBy(F.desc("count")))

language,count
Simplified Chinese,378
Japanese,96
Traditional Chinese,76
Russian,31
French,13
Korean,13
German,12
,10
Italian,8
Spanish - Spain,5
Portuguese - Brazil,5
English[b]*[/b],4
Polish,4
Thai,3
German[b]*[/b],2
Arabic,2
Spanish - Latin America,2
English Dutch English,1
Korean[b]*[/b],1
Czech,1
Spanish - Spain [b]*[/b],1
Japanese [b]*[/b],1
French[b]*[/b],1
English Russian Spanish - Spain Japanese Czech,1
Spanish - Spain[b]*[/b],1
Greek,1
Turkish,1
Russian [b]*[/b],1
Italian[b]*[/b],1
Russian English Spanish - Spain French Japanese Czech,1
Italian [b]*[/b],1

Databricks visualization. Run in Databricks to view.

Une très faible quantité de jeux ne supporte pas la langue anglaise. Après exploration, il s'avère que ce sont, dans la très grande majorité, des jeux chinois ou japonais.

### 6.2 Evolution du support des langues

In [0]:
# 1) explode + nettoyage
df_languages = (
    df.filter(F.col("release_year").isNotNull()& (F.col("release_year") >= 2006))
      .select("appid", "release_year", "languages")
      .withColumn("language", F.explode(F.split(F.coalesce(F.col("languages"), F.lit("")), ",")))
      .withColumn("language", F.trim(F.col("language")))
      .filter(F.col("language") != "")
      # retire "(...)" et "*"
      .withColumn("language", F.regexp_replace(F.col("language"), r"\(.*?\)", ""))
      .withColumn("language", F.regexp_replace(F.col("language"), r"\*", ""))
      .withColumn("language", F.trim(F.col("language")))
      .filter(F.col("language") != "")
      .select("appid", "release_year", "language")
      .dropDuplicates(["appid", "release_year", "language"])  # évite doubles comptages
)

# 2) top 10 langues globales
top_languages = (
    df_languages.groupBy("language")
    .agg(F.countDistinct("appid").alias("n_games"))
    .orderBy(F.desc("n_games"))
    .limit(10)
    .select("language")
)

df_languages_top = df_languages.join(top_languages, on="language", how="inner")

# 3) numérateur: nb jeux de l'année qui proposent cette langue
df_lang_year = (
    df_languages_top
    .groupBy("release_year", "language")
    .agg(F.countDistinct("appid").alias("n_games_lang"))
)

# 4) dénominateur: nb jeux sortis cette année (tous jeux)
df_year_total = (
    df.filter(F.col("release_year").isNotNull())
      .groupBy("release_year")
      .agg(F.countDistinct("appid").alias("n_games_year"))
)

# 5) part (%) = n_games_lang / n_games_year
df_lang_share = (
    df_lang_year.join(df_year_total, on="release_year", how="inner")
    .withColumn("share_pct", (F.col("n_games_lang") / F.col("n_games_year") * 100.0))
    .orderBy("release_year", F.desc("share_pct"))
)

display(df_lang_share)

release_year,language,n_games_lang,n_games_year,share_pct
2006,English,61,61,100.0
2006,French,25,61,40.98360655737705
2006,German,23,61,37.704918032786885
2006,Italian,21,61,34.42622950819672
2006,Spanish - Spain,19,61,31.147540983606557
2006,Russian,13,61,21.311475409836063
2006,Japanese,6,61,9.836065573770492
2006,Korean,4,61,6.557377049180328
2006,Simplified Chinese,4,61,6.557377049180328
2006,Portuguese - Brazil,1,61,1.639344262295082
2007,English,98,98,100.0
2007,French,48,98,48.97959183673469
2007,German,47,98,47.95918367346938
2007,Spanish - Spain,40,98,40.816326530612244
2007,Italian,40,98,40.816326530612244
2007,Russian,9,98,9.183673469387756
2007,Korean,6,98,6.122448979591836
2007,Japanese,5,98,5.1020408163265305
2007,Simplified Chinese,3,98,3.061224489795918
2007,Portuguese - Brazil,1,98,1.0204081632653061
2008,English,157,159,98.74213836477988
2008,French,65,159,40.88050314465409
2008,German,60,159,37.735849056603776
2008,Spanish - Spain,55,159,34.59119496855346
2008,Italian,52,159,32.70440251572327
2008,Russian,19,159,11.949685534591195
2008,Japanese,7,159,4.40251572327044
2008,Simplified Chinese,5,159,3.1446540880503147
2008,Korean,4,159,2.515723270440252
2008,Portuguese - Brazil,2,159,1.257861635220126
2009,English,307,311,98.71382636655949
2009,French,146,311,46.94533762057878
2009,German,141,311,45.337620578778136
2009,Spanish - Spain,124,311,39.87138263665595
2009,Italian,120,311,38.58520900321543
2009,Russian,54,311,17.363344051446948
2009,Japanese,21,311,6.752411575562702
2009,Korean,10,311,3.215434083601286
2009,Portuguese - Brazil,6,311,1.929260450160772
2009,Simplified Chinese,5,311,1.607717041800643
2010,English,288,288,100.0
2010,German,133,288,46.18055555555556
2010,French,115,288,39.93055555555556
2010,Spanish - Spain,110,288,38.19444444444444
2010,Italian,98,288,34.02777777777778
2010,Russian,43,288,14.930555555555555
2010,Japanese,21,288,7.291666666666667
2010,Korean,9,288,3.125
2010,Simplified Chinese,5,288,1.7361111111111112
2010,Portuguese - Brazil,1,288,0.3472222222222222
2011,English,267,267,100.0
2011,German,153,267,57.30337078651685
2011,French,141,267,52.80898876404494
2011,Spanish - Spain,130,267,48.68913857677903
2011,Italian,114,267,42.69662921348314
2011,Russian,62,267,23.220973782771537
2011,Japanese,28,267,10.486891385767791
2011,Korean,14,267,5.2434456928838955
2011,Simplified Chinese,11,267,4.119850187265917
2011,Portuguese - Brazil,8,267,2.9962546816479403
2012,English,342,345,99.1304347826087
2012,German,178,345,51.59420289855072
2012,French,161,345,46.666666666666664
2012,Spanish - Spain,149,345,43.188405797101446
2012,Italian,140,345,40.57971014492754
2012,Russian,91,345,26.3768115942029
2012,Japanese,58,345,16.81159420289855
2012,Portuguese - Brazil,25,345,7.246376811594203
2012,Korean,25,345,7.246376811594203
2012,Simplified Chinese,22,345,6.3768115942028984
2013,English,471,471,100.0
2013,German,281,471,59.660297239915074
2013,French,260,471,55.20169851380042
2013,Spanish - Spain,227,471,48.19532908704883
2013,Italian,223,471,47.346072186836516
2013,Russian,178,471,37.79193205944799
2013,Portuguese - Brazil,90,471,19.10828025477707
2013,Japanese,86,471,18.259023354564754
2013,Simplified Chinese,61,471,12.951167728237792
2013,Korean,51,471,10.828025477707007
2014,English,1555,1557,99.87154784842646
2014,German,631,1557,40.52665382145151
2014,French,583,1557,37.44380218368658
2014,Spanish - Spain,525,1557,33.71868978805395
2014,Italian,453,1557,29.09441233140655
2014,Russian,412,1557,26.461143224149
2014,Japanese,215,1557,13.808606294155426
2014,Portuguese - Brazil,193,1557,12.3956326268465
2014,Simplified Chinese,149,1557,9.569685292228645
2014,Korean,126,1557,8.092485549132949
2015,English,2569,2575,99.76699029126213
2015,German,827,2575,32.116504854368934
2015,French,762,2575,29.59223300970874
2015,Spanish - Spain,726,2575,28.194174757281555
2015,Russian,622,2575,24.155339805825243
2015,Italian,575,2575,22.330097087378643
2015,Japanese,421,2575,16.349514563106794
2015,Portuguese - Brazil,331,2575,12.854368932038835
2015,Simplified Chinese,275,2575,10.679611650485436
2015,Korean,211,2575,8.194174757281553
2016,English,4175,4185,99.7610513739546
2016,German,1068,4185,25.519713261648747
2016,French,1018,4185,24.324970131421743
2016,Spanish - Spain,951,4185,22.724014336917563
2016,Russian,936,4185,22.365591397849464
2016,Italian,710,4185,16.965352449223417
2016,Japanese,629,4185,15.029868578255675
2016,Simplified Chinese,621,4185,14.838709677419354
2016,Portuguese - Brazil,485,4185,11.589008363201913
2016,Korean,343,4185,8.195937873357229
2017,English,5974,6017,99.28535815190294
2017,German,1379,6017,22.918397872694033
2017,French,1322,6017,21.971081934518864
2017,Russian,1280,6017,21.273059664284528
2017,Spanish - Spain,1230,6017,20.44208077114841
2017,Simplified Chinese,1151,6017,19.129134119993353
2017,Japanese,945,6017,15.70550108027256
2017,Italian,904,6017,15.024098387900947
2017,Portuguese - Brazil,645,6017,10.719627721455876
2017,Korean,586,6017,9.739072627555261
2018,English,7586,7678,98.80177129460797
2018,Simplified Chinese,1805,7678,23.508726230789268
2018,Russian,1777,7678,23.144047929148215
2018,German,1722,7678,22.42771555092472
2018,French,1590,7678,20.708517843188332
2018,Spanish - Spain,1482,7678,19.30190153685856
2018,Japanese,1282,7678,16.697056525136755
2018,Italian,1081,7678,14.079187288356342
2018,Korean,842,7678,10.966397499348789
2018,Portuguese - Brazil,809,7678,10.53659807241469
2019,English,6788,6968,97.41676234213547
2019,Simplified Chinese,1823,6968,26.162456946039036
2019,Russian,1631,6968,23.407003444316878
2019,German,1605,6968,23.03386911595867
2019,French,1519,6968,21.799655568312286
2019,Spanish - Spain,1351,6968,19.388633754305395
2019,Japanese,1317,6968,18.900688863375432
2019,Italian,983,6968,14.107347876004592
2019,Korean,861,6968,12.356486796785305
2019,Portuguese - Brazil,778,6968,11.16532721010333
2020,English,8192,8305,98.63937387116195
2020,Simplified Chinese,2214,8305,26.65863937387116
2020,Russian,1967,8305,23.684527393136666
2020,German,1926,8305,23.190848886213125
2020,French,1894,8305,22.805538832028898
2020,Japanese,1727,8305,20.79470198675497
2020,Spanish - Spain,1693,8305,20.385310054184227
2020,Italian,1298,8305,15.62913907284768
2020,Korean,1097,8305,13.20891029500301
2020,Portuguese - Brazil,1043,8305,12.55869957856713
2021,English,8754,8823,99.21795307718463
2021,Simplified Chinese,2467,8823,27.961010993992975
2021,Russian,2197,8823,24.900827382976313
2021,German,2098,8823,23.77876005893687
2021,French,2055,8823,23.291397483849032
2021,Japanese,1923,8823,21.795307718463107
2021,Spanish - Spain,1846,8823,20.922588688654653
2021,Italian,1340,8823,15.187577921341946
2021,Portuguese - Brazil,1262,8823,14.303524878159358
2021,Korean,1254,8823,14.21285277116627
2022,English,7405,7455,99.32930918846412
2022,Simplified Chinese,2140,7455,28.70556673373575
2022,German,1691,7455,22.682763246143526
2022,French,1669,7455,22.38765928906774
2022,Japanese,1658,7455,22.240107310529847
2022,Russian,1601,7455,21.475519785378943
2022,Spanish - Spain,1526,7455,20.469483568075116
2022,Korean,1139,7455,15.27833668678739
2022,Italian,1106,7455,14.835680751173708
2022,Portuguese - Brazil,1058,7455,14.191817572099264

Databricks visualization. Run in Databricks to view.

- La quasi totalité des jeux propose l'anglais sur toute la période observée
- On note que la proportion de jeux proposant l'espagnol, le français, l'allemand ou l'italien a diminuée progressivement à partir de 2015 pour se stabiliser à partir de 2017. Ces proportions ont été divisées par 2 pour ces 4 langues.
- A part en 2013 où il y a une proportion étonnament importante de jeux proposant le russe comme langue, la part des jeux qui proposent cette langue reste relativement stable sur toute la période observée.
- A partir de 2012, le portugais (Brésil) émerge significativement mais se stabilise rapidement autour de 12% par an.
- A partir de 2013, émergence du chinois simplifié et progression régulière chaque année jusqu'en 2022.

# 7. Catégories

### 7.1 Grandes classes de catégories

In [0]:
total_games_categories = (
    df_categories
    .select("appid")
    .distinct()
    .count()
)

category_group_distribution = (
    df_categories
    .groupBy("category_group")
    .agg(F.countDistinct("appid").alias("nb_games"))
    .withColumn("proportion_games", F.col("nb_games") / F.lit(total_games_categories) * 100)
    .orderBy(F.desc("proportion_games"))
)

display(category_group_distribution)

category_group,nb_games,proportion_games
Gameplay mode,54421,99.45358187134504
Community / Social,28920,52.85087719298246
Device / Hardware support,27243,49.786184210526315
Monetization / Content,10253,18.737207602339183
Accessibility / UX,1178,2.1527777777777777

Databricks visualization. Run in Databricks to view.

On retrouve, pour la quasi totalité des jeux, une information sur le type de gameplay ("single player", "multi-player", "co-op").

Pour 52,9% des jeux, on retrouve ce que nous avons appelé une catégorie communautaire/sociale : existance d'achievements, de classsement des joueurs, un workshop pour les moddeurs.

Viennent ensuite les catégories liées aux outils supportés ou proposés par le jeu : "Steam Cloud", 'Controller Support", "VR Support" etc. pour lesquels une information est données pour 49,8% des jeux.

Enfin, 18,7% des jeux ont une catégorie affichée concernant un élément de monétisation tel que "trading cards", "VR Collectibles" ou "In-Game Purchases"

et seulement 2% des jeux ont une information sur l'accessibilité "Commentary available" ou "Captions available".

### 7.2 Catégories par classes analytiques

In [0]:
total_games_categories = (
    df_categories
    .select("appid")
    .distinct()
    .count()
)

category_distribution_grouped = (
    df_categories
    .groupBy("category_group", "category")
    .agg(F.countDistinct("appid").alias("nb_games"))
    .withColumn(
        "proportion_games",
        F.col("nb_games") / F.lit(total_games_categories) * 100
    )
)

# classement à l'intérieur de chaque classe analytique
w = Window.partitionBy("category_group").orderBy(F.desc("proportion_games"))

category_distribution_ranked = (
    category_distribution_grouped
    .withColumn("rank_in_group", F.row_number().over(w))
    .orderBy("category_group", "rank_in_group")
)

display(category_distribution_ranked)

category_group,category,nb_games,proportion_games,rank_in_group
Accessibility / UX,Captions available,1038,1.8969298245614035,1
Accessibility / UX,Commentary available,204,0.37280701754385964,2
Community / Social,Steam Achievements,27394,50.062134502923975,1
Community / Social,Steam Leaderboards,5509,10.067616959064328,2
Community / Social,Stats,2926,5.347222222222222,3
Community / Social,Includes level editor,1657,3.0281432748538015,4
Community / Social,Steam Workshop,1608,2.93859649122807,5
Community / Social,Valve Anti-Cheat enabled,111,0.20285087719298245,6
Community / Social,Includes Source SDK,44,0.08040935672514621,7
Community / Social,Mods,2,0.0036549707602339184,8
Community / Social,Mods (require HL2),2,0.0036549707602339184,9
Device / Hardware support,Steam Cloud,14235,26.014254385964914,1
Device / Hardware support,Full controller support,11878,21.706871345029242,2
Device / Hardware support,Partial Controller Support,7867,14.376827485380117,3
Device / Hardware support,Remote Play Together,4859,8.879751461988304,4
Device / Hardware support,Remote Play on TV,1941,3.5471491228070176,5
Device / Hardware support,Remote Play on Tablet,868,1.5862573099415203,6
Device / Hardware support,Remote Play on Phone,714,1.3048245614035088,7
Device / Hardware support,VR Support,237,0.4331140350877193,8
Gameplay mode,Single-player,52025,95.0749269005848,1
Gameplay mode,Multi-player,11455,20.933845029239766,2
Gameplay mode,PvP,7070,12.920321637426902,3
Gameplay mode,Co-op,5616,10.263157894736842,4
Gameplay mode,Online PvP,5025,9.18311403508772,5
Gameplay mode,Shared/Split Screen,4324,7.902046783625731,6
Gameplay mode,Shared/Split Screen PvP,3125,5.710891812865497,7
Gameplay mode,Online Co-op,2981,5.447733918128654,8
Gameplay mode,Shared/Split Screen Co-op,2450,4.47733918128655,9
Gameplay mode,Cross-Platform Multiplayer,1742,3.1834795321637426,10
Gameplay mode,MMO,787,1.4382309941520468,11
Gameplay mode,LAN PvP,474,0.8662280701754386,12
Gameplay mode,LAN Co-op,409,0.7474415204678363,13
Gameplay mode,Steam Turn Notifications,79,0.14437134502923976,14
Monetization / Content,Steam Trading Cards,9208,16.827485380116958,1
Monetization / Content,In-App Purchases,1349,2.4652777777777777,2
Monetization / Content,SteamVR Collectibles,40,0.07309941520467836,3

Databricks visualization. Run in Databricks to view.

Lorsqu'on observe la ventilation des catégories à l'intérieur des classes analytiques que nous avons créées :

- Community/Social : Les "Steam Achievements" sont renseignés dans 50% des jeux et les "Steam Leaderboards" dans 10%
- Device/Hardware support : "Steam Cloud" est rensiegné pour 26% des jeux suivi de "Full Controller Support" (21,7%)
- Gameplay Mode : 95% des jeux proposent un mode "Single Player" et 21% un mode "Multi-player". pour 13% des jeux, l'information est données de l'existence d'un "PvP" ("joueurs contre joueurs") et pour 10%, de la présence d'un mode "Co-op" ("Coopération).
- Monetization / Content : Pour 16,8% des jeux, il est indiqué l'exxistence de "Steam trading cards"

In [0]:
df_categories_perf = (
    df_categories
    .join(
        df.select(
            "appid",
            "owners_avg",
            "reviews_total",
            "pos_ratio",
            "steam_score",
            "price_eur"
        ),
        "appid"
    )
)

In [0]:
popular_games = (
    df
    .filter(
        (F.col("reviews_total") >= 20000) &
        (F.col("steam_score") >= 95)
    )
    .select("appid")
    .distinct()
)

### 7.3 Distribution des catégories Steam parmi les jeux populaires

In [0]:
popular_categories = (
    df_categories
    .join(popular_games, on="appid", how="inner")
    .groupBy("category_group", "category")
    .agg(F.countDistinct("appid").alias("popular_games_count"))
    .withColumn(
        "share_of_popular_games",
        F.col("popular_games_count") / F.lit(popular_games.count()) * 100
    )
    .orderBy(F.desc("share_of_popular_games"))
)

display(popular_categories)

category_group,category,popular_games_count,share_of_popular_games
Gameplay mode,Single-player,145,95.39473684210526
Community / Social,Steam Achievements,117,76.97368421052632
Device / Hardware support,Steam Cloud,111,73.02631578947368
Monetization / Content,Steam Trading Cards,90,59.210526315789465
Device / Hardware support,Full controller support,84,55.26315789473685
Device / Hardware support,Remote Play on Tablet,81,53.289473684210535
Device / Hardware support,Remote Play on Phone,64,42.10526315789473
Device / Hardware support,Remote Play on TV,56,36.84210526315789
Gameplay mode,Multi-player,55,36.18421052631579
Gameplay mode,Co-op,38,25.0
Community / Social,Steam Workshop,36,23.684210526315788
Gameplay mode,Online Co-op,30,19.736842105263158
Device / Hardware support,Remote Play Together,29,19.078947368421055
Community / Social,Includes level editor,27,17.763157894736842
Gameplay mode,Online PvP,23,15.131578947368421
Gameplay mode,PvP,23,15.131578947368421
Device / Hardware support,Partial Controller Support,21,13.815789473684212
Community / Social,Steam Leaderboards,18,11.842105263157894
Accessibility / UX,Captions available,18,11.842105263157894
Community / Social,Stats,15,9.868421052631579
Gameplay mode,Shared/Split Screen,15,9.868421052631579
Gameplay mode,Shared/Split Screen Co-op,14,9.210526315789473
Gameplay mode,Cross-Platform Multiplayer,10,6.578947368421052
Gameplay mode,Shared/Split Screen PvP,8,5.263157894736842
Community / Social,Includes Source SDK,8,5.263157894736842
Community / Social,Valve Anti-Cheat enabled,7,4.605263157894736
Accessibility / UX,Commentary available,6,3.9473684210526314
Gameplay mode,LAN Co-op,6,3.9473684210526314
Gameplay mode,LAN PvP,5,3.289473684210526
Device / Hardware support,VR Support,2,1.3157894736842104
Monetization / Content,In-App Purchases,2,1.3157894736842104

Databricks visualization. Run in Databricks to view.

Les catégories les plus souvent présentes parmis les jeux les plus populaires (ayant plus de 20 000 reviews et un Steam_Score >= 95) sont :

- Single-player
- Steam Achievements
- Steam Cloud

puis, dans un second temps, nous trouvons :

- Steam trading cards
- Full controller support
- Remote play on tablet

# 8. Genres et composition du catalogue

### 8.1 Genres les plus représentés

#### 8.1.1 Fréquences brutes d'apparition des genres dans le catalogue Steam

In [0]:
# Fréquence brute des genres
top_genres_frequency = (
    df_genres
    .groupBy("genre")
    .agg(F.countDistinct("appid").alias("nb_games"))
    .orderBy(F.desc("nb_games"))
    .limit(12)
)

display(top_genres_frequency)

genre,nb_games
Indie,39681
Action,23759
Casual,22086
Adventure,21431
Strategy,10895
Simulation,10836
RPG,9534
Early Access,6145
Free to Play,3393
Sports,2666
Racing,2155
Massively Multiplayer,1460

Databricks visualization. Run in Databricks to view.

#### 8.1.2 Proportion des jeux auxquels sont rattachés les genres dans le catalogue Steam

In [0]:
# Nombre total de jeux ayant au moins un genre renseigné
total_games = (
    df
    .filter(F.col("genre").isNotNull())
    .select("appid")
    .distinct()
    .count()
)

# Distribution globale des genres
df_genre_distribution = (
    df_genres
    .groupBy("genre")
    .agg(F.countDistinct("appid").alias("nb_games"))
    .withColumn("proportion", F.col("nb_games") / F.lit(total_games) * 100)
    .orderBy(F.desc("proportion"))
)

display(df_genre_distribution.limit(12))

genre,nb_games,proportion
Indie,39681,71.25336685221764
Action,23759,42.66295564733345
Casual,22086,39.658825641946486
Adventure,21431,38.48267193391992
Strategy,10895,19.563655952594722
Simulation,10836,19.45771233614653
RPG,9534,17.119770156221943
Early Access,6145,11.034297001256958
Free to Play,3393,6.09265577302927
Sports,2666,4.7872149398455734
Racing,2155,3.869635482133237
Massively Multiplayer,1460,2.6216555934638173

Databricks visualization. Run in Databricks to view.

Au moment de l'extraction on retrouve "Indie" (71,25% des jeux ont ce genre attaché) en tant que genre prédominant sur le catalogue Steam. viennent ensuite les genres "Action" (42,66%), Casual" (39,66%) et "Adventure" (38,48%).

il est important de rappeler que les genres ne sont pas exclusifs : un même jeu peut être associé à plusieurs genres. Les proportions observées ne décrivent donc pas une partition du catalogue mais plutôt la fréquence d’apparition de chaque genre parmi les jeux disponibles. Cette caractéristique limite l’interprétation des fréquences individuelles et invite à analyser plus précisément la manière dont les genres se combinent entre eux, ce qui sera exploré dans le second notebook.

### 8.2 Top 10 des genres les plus représentés dans les sorties par année

In [0]:

df_genres_year = (
    df
    .filter((F.col("release_year") >= 2012) & (F.col("release_year") <= 2022))
    .withColumn("genre", F.explode(F.split(F.col("genre"), ",")))
    .withColumn("genre", F.trim(F.col("genre")))
    .filter(F.col("genre") != "")
)


df_counts = (
    df_genres_year
    .groupBy("release_year", "genre")
    .count()
)


w = Window.partitionBy("release_year").orderBy(F.desc("count"), F.asc("genre"))

df_top10 = (
    df_counts
    .withColumn("rk", F.row_number().over(w))
    .filter(F.col("rk") <= 10)
    .drop("rk")
)

pdf = (
    df_top10
    .orderBy(F.desc("release_year"), F.desc("count"))
    .toPandas()
)

years = sorted(pdf["release_year"].unique(), reverse=True)

# Grille (ex: 3 colonnes)
ncols = 3
nrows = math.ceil(len(years) / ncols)

fig = make_subplots(
    rows=nrows, cols=ncols,
    subplot_titles=[str(y) for y in years],
    horizontal_spacing=0.08, vertical_spacing=0.12
)

for i, y in enumerate(years):
    r = i // ncols + 1
    c = i % ncols + 1

    d = pdf[pdf["release_year"] == y].sort_values("count", ascending=False)

    # Pour un bar chart lisible, le plus simple est horizontal
    fig.add_trace(
        go.Bar(
            x=d["count"],
            y=d["genre"],
            orientation="h",
            name=str(y),
            showlegend=False
        ),
        row=r, col=c
    )

    # Top en haut (barh -> inverser l’axe Y)
    fig.update_yaxes(autorange="reversed", row=r, col=c)

fig.update_layout(
    height=300*nrows,
    title_text="Top 10 genres par année (2012–2022)",
    margin=dict(l=40, r=20, t=60, b=30)
)

fig.show()

Sans surprise, le genre "Indie" est le plus représenté chaque année depuis 2013, de très loin.

dans le top 4, on retrouve également les mêmes genres chaque année : "casual", "Action" et "Adventure" qui sont souvent liés au genre "Indie" pour un même jeu.

On remarque que, depuis 2015, le genre "Early Access" est apparu dans ce top 10. Il s'agit en fait de jeu en cours de développement et vendus à un pris généralement plus bas que le prix final afin de financer la poursuite du développement en autorisant les joueurs à profiter du jeu tel qu'il est au cours du développement. C'est devenu une pratique courante de nos jours.

Les jeux "Free to Play" sont présents chaque année avec un volume régulier de sorties. Il s'agit de jeux gratuits dans lesquels le joueur peut dépenser de l'argent réel pour acquérir des ajouts cosmétiques ou pour simplifier sa progression.

Enfin, on retrouve les grands genres classiques du jeu vidéo : "Simulation" (Simulation de courses automobiles, de vol en avion, de vie), "Strategy", "RPG" (jeux de rôle) et "sports"

### 8.3 Poids des jeux "indie" dans les sorties de chaque année

In [0]:
# 1) Une ligne par jeu / genre
df_genres = (
    df.filter((F.col("release_year") >= 2012) & (F.col("release_year") <= 2022))
      .filter(F.col("release_year").isNotNull())
      .withColumn("genre", F.explode(F.split(F.col("genre"), ",")))
      .withColumn("genre", F.trim(F.col("genre")))
      .filter(F.col("genre") != "")
      .select("appid", "release_year", "genre")
      .dropDuplicates(["appid", "release_year", "genre"])
)

# 2) Nombre total de jeux par année
df_total_games_year = (
    df.filter((F.col("release_year") >= 2012) & (F.col("release_year") <= 2022))
      .filter(F.col("release_year").isNotNull())
      .groupBy("release_year")
      .agg(F.countDistinct("appid").alias("n_games_total"))
)

# 3) Nombre de jeux "Indie" par année
df_indie_games_year = (
    df_genres
    .filter(F.col("genre") == "Indie")
    .groupBy("release_year")
    .agg(F.countDistinct("appid").alias("n_games_indie"))
)

# 4) Jointure + proportion
df_indie_share = (
    df_total_games_year
    .join(df_indie_games_year, on="release_year", how="left")
    .na.fill(0, subset=["n_games_indie"])
    .withColumn(
        "indie_share_pct",
        F.round((F.col("n_games_indie") / F.col("n_games_total")) * 100, 2)
    )
    .orderBy("release_year")
)

display(df_indie_share)

release_year,n_games_total,n_games_indie,indie_share_pct
2012,345,173,50.14
2013,471,262,55.63
2014,1557,870,55.88
2015,2575,1847,71.73
2016,4185,2938,70.2
2017,6017,4263,70.85
2018,7678,5832,75.96
2019,6968,5266,75.57
2020,8305,6234,75.06
2021,8823,6363,72.12
2022,7455,5327,71.46

Databricks visualization. Run in Databricks to view.

### 8.4 Fréquence d'association d'autres genres à "Indie"

In [0]:
# Jeux contenant le genre Indie
indie_games = (
    df_genres
    .filter(F.col("genre") == "Indie")
    .select("appid")
    .distinct()
)

# Nombre total de jeux Indie
n_indie = indie_games.count()

# Genres associés aux jeux Indie
indie_genres = (
    df_genres
    .join(indie_games, on="appid", how="inner")
    .filter(F.col("genre") != "Indie")
)

# Comptage des genres associés
genres_associes = (
    indie_genres
    .groupBy("genre")
    .agg(F.countDistinct("appid").alias("n_games"))
)

# Proportion parmi les jeux Indie
genres_associes = genres_associes.withColumn(
    "proportion_indie",
    (F.col("n_games") / F.lit(n_indie)*100)
)

genres_associes = genres_associes.orderBy(F.desc("proportion_indie"))

display(
    genres_associes
    .orderBy(F.desc("proportion_indie"))
    .limit(10)
)

genre,n_games,proportion_indie
Action,18242,46.32888888888888
Casual,17092,43.408253968253966
Adventure,16558,42.05206349206349
Strategy,7766,19.723174603174602
Simulation,7645,19.415873015873018
RPG,7101,18.034285714285716
Early Access,4835,12.279365079365078
Free to Play,2267,5.757460317460318
Sports,1712,4.347936507936508
Racing,1439,3.6546031746031744

Databricks visualization. Run in Databricks to view.

Le graphique ci-dessus présente, parmis tous les jeux ayant le genre "Indie" associé, les 10 genres les plus couramment associés.

On retrouve donc, pour 46% des jeux avec le genre "Indie" rattaché, également le genre "Action". Pour 43%, le genre "Casual" et pour 42%, le genre "Adventure". Ce sont les 3 genres les plus fréquemment rattachés à un jeu en association à "Indie". Viennent ensuite "Strategy" (20%), "Simulation" (19%) et "RPG" (18%)

Cela montre, finalement, que le genre "Indie" constitue une catégorie transversale plutôt qu'un genre au sens strict et se marie avec une grande variété d'autres genres. "Indie" décrit plutôt un mode de production, indiquant qu'un jeu est développé par un studio indépendant

il est important de rappeler que les genres ne sont pas exclusifs : un même jeu peut être associé à plusieurs genres. Les proportions observées ne décrivent donc pas une partition du catalogue mais plutôt la fréquence d’apparition de chaque genre parmi les jeux disponibles. Cette caractéristique limite l’interprétation des fréquences individuelles et invite à analyser plus précisément la manière dont les genres se combinent entre eux, ce qui sera exploré dans le notebook suivant.

# 9. Synthèse de la structure du catalogue Steam

L'analyse du catalogue Steam met en exergue plusieurs caractéristiques.

Tout d’abord, le nombre de jeux publiés augmente fortement au fil du temps, ce qui traduit une croissance rapide du catalogue et une ouverture progressive de la plateforme à un nombre croissant de développeurs. Cette expansion s’accompagne d’une fragmentation marquée des éditeurs : si quelques studios publient de nombreux titres, la majorité des éditeurs ne proposent qu’un nombre limité de jeux.

Sur le plan technique, le catalogue reste très largement centré sur l’écosystème Windows, tandis que les versions Mac et Linux apparaissent beaucoup plus minoritaires.

Par ailleurs, L’analyse des catégories de gameplay montre également que le mode Single-player reste très largement représenté dans le catalogue, même si de nombreuses productions intègrent également des fonctionnalités multijoueur. 

Enfin, le tag Indie domine très nettement la distribution des genres, ce qui reflète la forte présence des productions indépendantes sur la plateforme. Cependant, malgré cette domination, le catalogue conserve une grande diversité de genres, couvrant un large éventail de types de jeux et de styles de gameplay.

Dans l’ensemble, ces éléments décrivent un catalogue très étendu, ouvert à une grande variété de studios et de genres, mais fortement marqué par la place centrale des productions indépendantes et par la prédominance de l’écosystème Windows.

Après cette description de la structure du catalogue Steam, le second notebook s’intéresse aux relations entre genres et à plusieurs dimensions économiques et de réception des jeux.